### ISSUE TITLE
Character Importance-Slider memorize importance of last character ... partly

### ISSUE THREAD

**Issue by ScullyBlue** [olivierkes/manuskript#102]
I have created one character with high importance (Main) and when I create a new one, the importance-slider is also on high importance, but in the sidebar the second character stand under low importance (Minor). If I want the character move to the category Main I must set the importance-slider back to Minor and then to Main.

Not very important, but at first it confused me, because the importance of the character was high (on Slider) and the character stands in the list under low importance.

I used manuscript 0.3.0 on Linux Mint 18, 64-bit.

**Comment by olivierkes** [comment]
Thanks for reporting that. Annoying stuff... I'll have a look when possible.

**Comment by gedakc** [comment]
@ScullyBlue I created a Pull Request to address this issue.  The PR enhancement makes the Character Importance slider work the same way as the Plot Importance slider currently works.  More specifically with the enhancement, newly added records will default to the lowest importance.

This seemed to me to be a more correct choice because a user could be on any Character Tab (Basic infos, Summary, Notes, Detailed Infos) when the **+** button is clicked to add a new character.  Only the Basic infos tab shows the Importance slider, which is a piece of data for the current character only.

**Comment by ScullyBlue** [comment]
Thanks, gedakc, that sounds good.

**Comment by ScullyBlue** [comment]
My fault, wrong button ...

**Comment by gedakc** [comment]
The above referenced fixes have been committed to the develop branch for inclusion in the upcoming 0.5.0 release.

**Comment by gedakc** [comment]
@olivierkes can you close this report?  The fix to address the issue has already been committed (see above).
