### ISSUE TITLE
What would a newbie need to learn to contribute to this project?

### ISSUE THREAD

**Issue by TurkyDev** [olivierkes/manuskript#1020]
I can see it says Python3 and pyqt5, also see javascript?

Is that it? are there more specific things?
I really like this program and would like to help its development in the future, but i am very new to this open source stuff.
Would love a checklist of what me and other newbies need to learn first.

**Comment by TheJackiMonster** [comment]
I think if you want to contribute as developer, learning Python makes most sense and also looking into Qt. Otherwise it is also helpful if some people test the software, look for issues with the user experience and design. One thing which everyone can do as well is to contribute to the translations via [weblate](https://hosted.weblate.org/projects/manuskript/translations/).
