### ISSUE TITLE
[Feature Request] Full Compile Export

### ISSUE THREAD

**Issue by timaeos** [olivierkes/manuskript#1034]
My apologies if this has been requested before:

Would it be possible to include a Full Compile export that includes all of the sections in the export? This could allow for integrating into a Git or Svn version control system on top which could allow for collaborative and shared story writing without needing to swap msk files back and forth. This would allow for parallelized project work and merging.

![image](https://user-images.githubusercontent.com/104638316/166342775-1d2ad737-6028-4306-8e3f-708282b30ea9.png)

Each Section could be a separate file with accompanying markdown formatting. It wouldn't be able to necessarily integrate images but could be useful for collaborative use cases. 
 
- General Information
      - Author
      - Book Information
- Summary
      - Situation
      - Summaries
- Characters
      - Main
           - Name
                - Basic Info
                - Summary
                - Notes
           - Name
           - .
           - . 
      - Secondary
           - Name
                - Basic Info
                - Summary
                - Notes
           - Name
           - .
           - .
      - Minor
           - Name
                - Basic Info
                - Summary
                - Notes
           - Name
           - .
           - .
- Plots
- World

- Editor

I appreciate the project and hope to contribute in some form in the future.

**Comment by TheJackiMonster** [comment]
Have you tried the setting to save projects as directory instead of one single file. In that case you should already have an .msk file which will only contain the projects format version and won't change. The other parts of your project will then mostly stored as markdown files in a directory with the same name next to it.

You should be able to sync this folder with SVN or GIT without issues. The other files are partially XML sub-languages or even plain text files. So all of that should be quite reasonable for any collaboration via GIT.

But maybe that's not exactly what you want? Do you want to have everything in a single file?

**Comment by timaeos** [comment]
I was unaware that the multi-file option was there. My apologies. I think that should be sufficient for my use case at the moment. Thanks for the quick response!
