### ISSUE TITLE
No distance between two scenes in compiled document

### ISSUE THREAD

**Issue by ScullyBlue** [olivierkes/manuskript#104]
I have compiled my Work for Testing in ODT-Format (lookes mostly nice :+1: ), but between the scenes there is no visible gap. IMO it would be nice, if the user can adjust the preferences for paragraphes or setting number of breaks between scenes in the compiled document befor compiling.

(Tested with manuscript 0.3.0-linux on linux mint 18 64-Bit)

**Comment by olivierkes** [comment]
Hi,
This has been added to manuskript 0.4.0, in the new export dialog:
![export-preview-3](https://cloud.githubusercontent.com/assets/1192933/26459544/1cd42c78-4177-11e7-89f0-1e444ff3999e.jpg)

**Comment by gedakc** [comment]
@ScullyBlue, since you are on GNU/Linux and if you are creating a novel, you might take a look at [EBookGenTools](https://ebookgentools.sourceforge.net) which produces HTML, EPUB, MOBI, and DOC formats for Novels.

It does have a few extra requirements like specifying three equal "=" signs at the end of each scene, providing a cover image, and creating a configuration file.  The resulting DOC format uses styles so you can edit the paragraph styles to your liking.

Note that the **EBookGenTools** scripts have been updated to take exported text content from **Manuskript** to produce the above listed output formats.
