### ISSUE TITLE
Version 0.15 release date

### ISSUE THREAD

**Issue by EugeneUvin** [olivierkes/manuskript#1050]
When is planned release date for version 0.15? I'd like to complete Ukrainian UI translation before that date so that version has Ukrainian UI 100% supported.

**Comment by TheJackiMonster** [comment]
There are no planned release dates. I usually try to make a release each half a year but it also depends on the contributions. You definitely have some time to complete that. Would be neat to have full coverage. ^^

**Comment by EugeneUvin** [comment]
Got it, thank you. I will need to translate and proofread and then update you here. Ukrainian is my second language, so I'll need to make sure all the intricacies of UI language are captured.

**Comment by EugeneUvin** [comment]
Hi @TheJackiMonster I feel like I've proofread the translation enough to include it. Except of current issues #1052 it should be fine. The translation is in Weblate; I tried to attache a qm file, but failed - I'll see if I can make a commit with that.

**Comment by EugeneUvin** [comment]
Hi @TheJackiMonster I hope my proposition is not too audacious: for a release with Ukrainian translation would it be acceptable to include a demo project with a Ukrainian classical novel? If you agree, I can prepare the very famous Ivan Franko's "Zakhar Berkut", which is in Public Domain https://uk.wikisource.org/wiki/%D0%A2%D0%B2%D0%BE%D1%80%D0%B8_(%D0%A4%D1%80%D0%B0%D0%BD%D0%BA%D0%BE,_1956%E2%80%931962)/13/%D0%97%D0%B0%D1%85%D0%B0%D1%80_%D0%91%D0%B5%D1%80%D0%BA%D1%83%D1%82

Having that + #1053 would help me to promote Manuskript in Ukrainian amateur writer society, which grows in number right now.

**Comment by TheJackiMonster** [comment]
I assume technically we could add a demo project similar to the existing one. But this would also increase the installation size for everyone... so I would probably recommend sticking to something not too long. Best case the example would also add a different type of project structure.

Otherwise it could also make sense to make a fork of Manuskript which ships different examples depending on the preferred language.

But I don't know the numbers at the moment to be sure, it's smart to do so. If the example project doesn't add too much, it should be fine, I assume. Maybe we could add an example for every language with 100% coverage then. Most important is the licensing which needs to be fine with a GPL3 re-publication.

**Comment by TheJackiMonster** [comment]
> I tried to attache a qm file, but failed - I'll see if I can make a commit with that.

Don't worry. I will generate the .qm files for all changed languages after merging the state from Weblate. ^^

**Comment by EugeneUvin** [comment]
> > I tried to attache a qm file, but failed - I'll see if I can make a commit with that.
> 
> Don't worry. I will generate the .qm files for all changed languages after merging the state from Weblate. ^^

Hi @TheJackiMonster looks like no need for that - my PR was merged.

**Comment by EugeneUvin** [comment]
I've confused merging PR with approving it... Need to get used to GitHub notifications.

**Comment by TheJackiMonster** [comment]
I will make the release of 0.15.0 soon. Please make sure that the translation in [Weblate](https://hosted.weblate.org/projects/manuskript/translations/) looks good to go. I will merge latest changes from there before the actual release in the next weeks.
