### ISSUE TITLE
Translation - missing lines in .ts file etc. issues

### ISSUE THREAD

**Issue by EugeneUvin** [olivierkes/manuskript#1052]
While testing Ukrainian translation in 0.14 Flatpak version on x86_64 Linux, I've ran into following issues: see screenshots.
![non-tranlatable-export1](https://user-images.githubusercontent.com/9447963/180620628-f37b8311-6478-471d-b0aa-fc3d44473982.png)
![non-translatable-export2](https://user-images.githubusercontent.com/9447963/180620629-410c0f5b-3f3e-4a9b-809d-e9e7d8f75dd7.png)
![non-translatable-export3](https://user-images.githubusercontent.com/9447963/180620630-f092b585-023b-4079-b7dc-c7981f774bff.png)
![non-translatable-import1](https://user-images.githubusercontent.com/9447963/180620631-76cac195-886e-48bd-8550-642eccd06256.png)
![non-translatable-import2](https://user-images.githubusercontent.com/9447963/180620632-3621bb0f-42b7-4834-8094-7e0a12f42a2c.png)
![non-translatable-manuskript-split-menu](https://user-images.githubusercontent.com/9447963/180620633-2280ff78-82e6-4259-bd01-f86083002027.png)
![non-translatable-manuskript1](https://user-images.githubusercontent.com/9447963/180620634-26320da5-632b-4716-b367-4ac158470b58.png)
![non-translatable-manuskript2](https://user-images.githubusercontent.com/9447963/180620635-d63c53d4-0e27-43d1-a898-286887f0d915.png)
![non-translatable-manuskript3](https://user-images.githubusercontent.com/9447963/180620636-6d920779-df58-4f3b-bda3-c929d25dde03.png)
![non-translatable-manuskript4](https://user-images.githubusercontent.com/9447963/180620637-00471056-d443-4e0a-bd64-03c8a99f6568.png)
![non-translatable-manuskript5 1](https://user-images.githubusercontent.com/9447963/180620638-1db7ae03-a942-4835-bb0e-5a717b727938.png)
![non-translatable-manuskript5 2](https://user-images.githubusercontent.com/9447963/180620639-1fbdf03a-3ca4-4758-b8cc-3a274cbe6b16.png)
![too-narrow-to-fit-titles](https://user-images.githubusercontent.com/9447963/180620640-73e665f5-2485-4b82-8750-86bebc00cecf.png)
![non-translatable-new-character](https://user-images.githubusercontent.com/9447963/180620820-4e81d977-32f1-47a2-8d75-a81e6dc311eb.png)
![non-translatable-new-plot](https://user-images.githubusercontent.com/9447963/180620823-45981ae8-5c0d-481d-a1e3-ccd7a01e1b9d.png)

**Comment by TheJackiMonster** [comment]
I think the numbers need to be addressed in a different way. I'm not sure whether translation files allow changing their format. But maybe it's possible to format them regarding the system settings.

Otherwise I've tried to fix the other issues (0e342337dd47d428f2978d8e75a64d7533d0c3d7). Some of them weren't hooked up with any translation at all. Others should actually exist in the translation files (for example the missing entry in a hero's journey... the code handles it the same way as all the other options).

Then the problem specific to Ukrainian with the label "Name". Maybe we can add an invisible character to them depending on the use case in the UI to split meanings. But I assume all other languages will require to patch their translation then.

**Comment by EugeneUvin** [comment]
"Name": for other languages, I can duplicate their current translation, as
they use the same word currently, i.e. it is already known.

вт, 9 авг. 2022 г., 14:46 Tobias Frisch ***@***.***>:

**Comment by TheJackiMonster** [comment]
I've updated all language- and translation files now ( #1133 ). I think the missing strings should now appear on Weblate and can be translated.

**Comment by TuxIoannes** [comment]
Hello, I added missing lines.
