### ISSUE TITLE
Crash when opening a plot in the cheat sheet containing deleted characters

### ISSUE THREAD

**Issue by Anne501R** [olivierkes/manuskript#1082]
When I open a specific plot in the cheat sheet view, Manuskript crashes. The error log says:

<pre>2022-10-08 11:03:13,529 - manuskript.logging - CRITICAL - An unhandled exception has occurred!
Traceback (most recent call last):
  File "manuskript\ui\cheatSheet.py", line 155, in showInfos
  File "manuskript\models\references.py", line 306, in infos
AttributeError: 'NoneType' object has no attribute 'name'</pre>

The error occured due to a character that I deleted in the character list, but was still referenced in the 'Basic Info' > 'Character(s)' field of this plot.

Workaround / fix: manually delete empty character reference in 'Basic Infos'

**Comment by TheJackiMonster** [comment]
Okay, I could reproduce it. The actual issue is likely that a character won't get removed from plots even though it has been deleted. Then the application tries to access a name of an invalid entry.

I've implemented a quick fix for the crash. But the invalid character reference stays for now. However in the newer efforts of refactoring Manuskript this issue should get resolved completely.
