### ISSUE TITLE
Disable Alt+Tab in Lock Screen mode.

### ISSUE THREAD

**Issue by MaqsudMallick** [olivierkes/manuskript#1090]
It seems that you can easily escape the Lock/Focus Mode using Alt + Tab. At present only Esc and F11 seem to be disabled. But its no point if I can just do Atl + Tab

**Comment by TheJackiMonster** [comment]
The mode is not supposed to lock you down into a sandbox without possibility to escape. It's goal is to avoid visual distractions. You don't have to press Alt + Tab during write, do you? I mean if you would press it occasionally while writing as accident, there might be a reason to disable it... but it's a function of your operating system rather than the application. So you could already look into disabling it the functionality for you locally?
