### ISSUE TITLE
0.14 won't open

### ISSUE THREAD

**Issue by ATL-KNH** [olivierkes/manuskript#1105]
"Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/ui/welcome.py", line 88, in showEvent
    self.mw.loadProject(last)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 614, in loadProject
    self.loadDatas(project)
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 900, in loadDatas
    errors = loadSave.loadProject(project)
  File "/usr/share/manuskript/manuskript/loadSave.py", line 60, in loadProject
    version = int(f.read())
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 10: invalid start byte"

Here's the traceback I get when I try to start Manuskript after unpacking 0-14.0-1.deb

**Comment by TheShadowOfHassen** [comment]
When unpacking do you mean installing or actually unzipping the .deb file?

**Comment by ATL-KNH** [comment]
installing according to the instructions provided. OS Ubuntu 22.04.01.

**Comment by TheShadowOfHassen** [comment]
So did you have your manuskript set to automatically open the last project? If so it could be that the file isn't there but honestly it looks like an error I had with the gtk port with a bad save file. Does anyone know where manuskript keeps its setting data? Because if you deleted that it should reset to normal.

If that's not the issue I think maybe trying to uninstall it and reinstall it.(Maybe update the computer and restart?) I don't think its a bug. I run 22.04 and I don't get it.

**Comment by TheJackiMonster** [comment]
The settings are stored in `~/.config/manuskript/manuskript.conf` if you want to change or delete them manually.

**Comment by TheShadowOfHassen** [comment]
So were you able to figure it out?

**Comment by ATL-KNH** [comment]
yes. thank you for your time. I removed the .conf and reinstalled.
