### ISSUE TITLE
Adding a clearer discription to contributing guidlines

### ISSUE THREAD

**Issue by TheShadowOfHassen** [olivierkes/manuskript#1115]
I am not bitter or upset in having to do things for my gtk pull request #1113 But I didn't see that in the contributing guidelines:

https://github.com/olivierkes/manuskript/wiki/Contributing-guidelines-for-developers

Is it just general github manners that I don't know or are the rules for manuskript? If its manuskript spacific rules I'll ad it to the wiki.

**Comment by TheJackiMonster** [comment]
No, that is pretty much just usual. Removing or breaking the `.gitignore` file won't get merged anywhere, I assume. Then adding unnecessary files is also something to avoid in general since when you start uploading such stuff, everyone does, the repository gets huge and new contributors need to download a lot of stuff, they don't need, to develop.

I can definitely add such things like not uploading backup files. But for example committing example projects is not a rule that does apply in every case. I know that your PR was not about adding another sample project. So I looked into those files and realized those were duplicates. But other PRs could contain such projects intentionally (there are actually issues about this, next to adding templates for example).

Then with the backup files. I could add a hint in the guidelines. But I won't know how these files look upfront since contributors could use all kinds of editors, IDEs and such. What I do is adding those filenames to the `.gitignore` when I have them myself flying around to not commit them accidentally.

Hope this makes sense.

**Comment by TheShadowOfHassen** [comment]
Ok got it. Thanks. I'll close the issue and I'll remeber what I did wrong.
