### ISSUE TITLE
Trojan in current windows installer?

### ISSUE THREAD

**Issue by sanjodito** [olivierkes/manuskript#112]
I downloaded the windows zip file of version 0.4.0 today from the Manuskript website and upon extracting it, McAfee immediately quarantined 5 objects as a Trojan.  I can only see a partial output of the quarantine information, but it shows "Detected as: Artemis!0D40325EC..."  I don't know if that was the file name or the signature that it detected, however, as I can't view the full log.

**Comment by gedakc** [comment]
Unfortunately some anti-virus software detect a false positive with this file, as is [sometimes the case with files created with pyInstaller](https://github.com/pyinstaller/pyinstaller/issues/847).

I created the 0.4.0 windows version so that it compatible all the way back to Windows XP.  Unfortunately this means using older versions of PyInstaller that seem to have this false positive identification that can cause undue concern.

If you are uncomfortable running from the windows installer, then you can instead opt to [Run Manuskript from Source Code on Windows](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows).

**Comment by sanjodito** [comment]
Thanks for the quick response.  I didn't see that this was an issue with an older version, so thought I would bring it to your attention.

**Comment by gedakc** [comment]
@sanjodito we appreciate receiving your report.  Other users may also encounter this issue and at least now they can view this issue to learn about the false positive identification.

**Comment by olivierkes** [comment]
Thanks for that. I reported it on the [website's download page](http://www.theologeek.ch/manuskript/download/) with a link to this issue.
Since it's not a manuskript issue, I'll close it here.
