### ISSUE TITLE
Feature request: Development version indicator

### ISSUE THREAD

**Issue by jrstrick** [olivierkes/manuskript#1126]
Could development versions please have some kind of identification, so I know whether I'm talking about/looking at the GTK version or the QT version? Versioning would be nice too, but probably much harder to impliment.

**Comment by TheShadowOfHassen** [comment]
So do you mean when you run it or in the github code page? GTK has been banished to a separate branch so that's more of a GitHub thing. If you mean in the different repository/branches. In my gtk pull request I added a clear statement in of it being a GTK unstable release in the about. It hasn't been merged though. Yet.  We haven't changed the README's or anything because we wanted the GTK to replace QT and writing out a README is less priority than the story.

Granted itshould be able to tell the difference between Gtk and Qt. You'll only be able to run Gtk in Linux without a lot of headache. You have to run something called test.io to get it to work. Also there is a massive Ui file with .glade files. and, at least on my computer it looks a lot different. You should be able to tell if you go to the about and if your about has tabs it's GTK.

Did this answer your question? I really don't understand what else you could mean.

**Comment by TheJackiMonster** [comment]
I think we could add the hash and datetime as a hint somewhere from the latest commit when the application is run from source code (assuming it has been cloned from Github of course). If the code is just downloaded, there isn't much we can do because I don't think changing a version string in a file with each single commit makes a lot of sense (potentially making merges pretty annoying). ^^'

**Comment by jrstrick** [comment]
I may be having a github newbie error, to be honest. I thought I had tried the gtk version, but every time I was pulling the QT version. I discovered this because I finally did manage to pull the GTK version, and as you say, getting it to run at all proved difficult. On looking more closely at help, about, it clearly shows that the QT library is in use. I'll go ahead and close this. Thanks.
