### ISSUE TITLE
Cheat sheet, how to disable separate window

### ISSUE THREAD

**Issue by functionsAsIntended** [olivierkes/manuskript#1158]
I accidentally clicked on "open in separate window" checking what Cheat Sheet was, and now i have no idea how to put it back where it was on the right side. My OS is Fedora 38 workstation, GNOME, installed with RPM package without any noticable issues.
How do i put it back? I like it there, hopefully i won't need a reinstall.

![image](https://user-images.githubusercontent.com/119619356/231537514-cdb88349-4a00-4a11-bbda-11a967593904.png)

**Comment by TheShadowOfHassen** [comment]
So I've had some issues with that. I think I either quit it or dragged it on top of one of the other items on the side(Cheat Sheet, Search or something) and it slid into place.

Honestly that "feature" may need to just be removed because I can think of 0 times where that would be useful and it gets in the way.

**Comment by obw** [comment]
> @TheShadowOfHassen 
> Honestly that "feature" may need to just be removed because I can think of 0 times where that would be useful and it gets in the way.

Well I know a place where this is useful, because I use it often. If you have a multiscreen setup! At the moment I 'reuse/misuse' the fullscreen mode, normal GUI on the left monitor and on the right fullscreen for editing. Sometimes when I have Chapters where I must keep track of the world (Places), characters and also old chapters, this feature is quite Useful!

Sometimes I use even VNC when I need more viewing real estate (Mostly when debugging Web applications)

What its look like is shown in this Screenshot. My normal two Screen Layout:

![dualscreen](https://user-images.githubusercontent.com/3050806/232233319-1a1d7b8b-5c8f-44cb-b10d-5e73d7e9c20a.png)

A better multiscreen support is something to work on, at a later state!

Regards

**Comment by TheShadowOfHassen** [comment]
I don't use two monitors because I have a laptop. But your idea is kind of smart. I want to redo full-screen in Gtk and it'd be cool to add features like that.

**Comment by alfar** [comment]
Not sure if it works the same on all operating systems, but for me on windows, double-clicking the title bar of the window made it pop back into place.
