### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by xiscofalpo** [olivierkes/manuskript#1183]
I am a graphic designer and I think I can help (for free) in the graphics part of Manuskript or in whatever is needed, I really like the project and that is why I want to help.

**Comment by TheJackiMonster** [comment]
You can go through the issues here on Github and see what you can do. I'm not sure how many issues fit graphical design though but I think there were some I flagged with the UI tag regarding icons, theming and such.

If you have any own ideas how to contribute, just open an issue to discuss or present it. ^^

**Comment by xiscofalpo** [comment]
sure <3

**Comment by TheShadowOfHassen** [comment]
Also we're working on a GTK port and you could check that out.

**Comment by TheJackiMonster** [comment]
Right, for the GTK port will likely use symbolic icons in most cases because they work very well with default light and dark theme. I assume you could also help by providing feedback for visual elements and UI design. Would also help with the current Qt application but in case we replace it with the GTK port in the future, the changes might not translate.

**Comment by xiscofalpo** [comment]
I'm so sorry for the delay in responding, it's been a busy week. I wanted to take the time to review each option and tool in the application in detail, and I think I can give a little feedback:

**UX:**
for example, sections such as "general" and "summary" can be integrated into one, since the information from both can be shared. Regarding the characters section, I think it could be an addition to be able to put an image of the character in addition to being able to create a relationship with other characters, I know that at the level of performance and implementations it would be complicated but perhaps include the option to add images in the panel of "world" and that can be consulted in the "cheat sheet" would be great.
I think that in addition to the storyline, a chronological timeline could be put in order to better order the events of the chapters, especially for fiction and fantasy stories that usually have broader time ranges, such a tool can benefit from maintaining coherence Within the story and being able to have it on the cheat sheet would also be perfect.
I also suggest putting a "notes" tool where you can put notes on topics and loose ideas more quickly

**UI:**
I am including a preview of icons that could be used based on the tools that are currently being used, if necessary I can modify the sizes and formats that are required, I would suggest keeping flat colors to make it easier to adapt them to the light and night versions more easily.
I made a somewhat more minimalist proposal, but to be honest, the original design in terms of the functionality that you have is very good and fluid. I made a small design proposal, but I'm not familiar with gtk, so I'm not sure how flexible it will be when it comes to writing through gtk, but I can learn it so I can help.

In addition to that, I apologize since my first language is not English I may have some errors.

footnote: the color is not of the final result, in early stages I like to work in grayscales or duotone, use msk for the file save extension, do not give it importance, just use it to fill the space where it will be the logo

![manuskript_iconos](https://github.com/olivierkes/manuskript/assets/81485882/55f59ede-5e48-4b9c-a17a-c751acabff37)
![manuskript_linea de tiempo](https://github.com/olivierkes/manuskript/assets/81485882/a61daa63-e038-4091-96cb-b454151ac68c)
![manuskript_minimalista redaccion](https://github.com/olivierkes/manuskript/assets/81485882/ba32277a-e64a-4586-8459-6cf4a0fa0d6a)

**Comment by xiscofalpo** [comment]
I'm so sorry for the delay in responding, it's been a busy week. I wanted to take the time to review each option and tool in the application in detail, and I think I can give a little feedback:

UX:
for example, sections such as "general" and "summary" can be integrated into one, since the information from both can be shared. Regarding the characters section, I think it could be an addition to be able to put an image of the character in addition to being able to create a relationship with other characters, I know that at the level of performance and implementations it would be complicated but perhaps include the option to add images in the panel of "world" and that can be consulted in the "cheat sheet" would be great.
I think that in addition to the storyline, a chronological timeline could be put in order to better order the events of the chapters, especially for fiction and fantasy stories that usually have broader time ranges, such a tool can benefit from maintaining coherence Within the story and being able to have it on the cheat sheet would also be perfect.
I also suggest putting a "notes" tool where you can put notes on topics and loose ideas more quickly

UI:
I am including a preview of icons that could be used based on the tools that are currently being used, if necessary I can modify the sizes and formats that are required, I would suggest keeping flat colors to make it easier to adapt them to the light and night versions more easily.
I made a somewhat more minimalist proposal, but to be honest, the original design in terms of the functionality that you have is very good and fluid. I made a small design proposal, but I'm not familiar with gtk, so I'm not sure how flexible it will be when it comes to writing through gtk, but I can learn it so I can help.

In addition to that, I apologize since my first language is not English I may have some errors.
footnote: the color is not of the final result, in early stages I like to work in grayscales or duotone, and I have used "msk" because the file save extension, do not give it importance, i just use it to fill the space where it will be the logo provisionally.

![manuskript_iconos](https://github.com/olivierkes/manuskript/assets/81485882/e925a04e-513e-47fa-a21e-0b68e61316f5)
![manuskript_linea de tiempo](https://github.com/olivierkes/manuskript/assets/81485882/02a6b17f-96c8-4b5c-afa2-9b16381d409f)
![manuskript_minimalista redaccion](https://github.com/olivierkes/manuskript/assets/81485882/f3636c9f-d22e-4730-b145-f8771d334546)

**Comment by TheJackiMonster** [comment]
I think the icons look quite good. I'm not sure though whether we should use that much padding around a navigation like this because in long term I actually want to have it working on devices like a Pinephone or Librem 5 as well (maybe that translates to Android devices in the future too which was requested in the past: https://github.com/olivierkes/manuskript/issues/942, https://github.com/olivierkes/manuskript/issues/912). So being space efficient is key.

As idea for the ".msk" icon: You could make a stylistic/symbolic icon of the logo.

About the storyline: I think there are already another issues opened regarding changes of the storyline with timing features (https://github.com/olivierkes/manuskript/issues/118). However the issue with a simple chronological timeline is that we don't actually know what people are writing with Manuskript.

For example I have personally used Bibisco in the past which is another great open-source writing tool. It provides a chronological order timeline for your scenes. However I noticed that you can run into issues when the order of your scenes in story is not necessarily chronological. Your characters could remember a scene in the past, a character might have a vision of the future or a character might even time-travel.

The most chaotic would be that you write a story with a decision tree with multiple scenes having the same timing potentially but not necessarily. Now if I wanted to implement a timeline for Manuskript, I'd like to support all of these cases because not supporting such cases might nodge an author into a direction to fit their story into the UX. But that should not be the goal.

It's also difficult if you even have chronological timings between scenes in your story but the time is not quite linear. For example between one scene and the next one could be a difference of thousands of years while the next scene might happen 15 minutes later. So you don't get a homogeneous density of events on your timeline which provides the opposite effect when looking at it because you don't find anything easily.

So for a proper timeline, we would actually need a non-linear approach regarding the context of each scene and its closest neighbors to group them into a reasonable interval. Also units need to be fully customizable because worlds could use an alternate approach to measure time. For example when you have two moons at a planet, you might have two different calendars for the same timeline. Both of them might still affect the behavior of different characters in your story.

Anyway, all I want to say is that feature discussion should likely be done in its specific issue because nothing is ever as easy as you might think on first glance. ^^'

**Comment by TheShadowOfHassen** [comment]
This would be better suited as a discussion, but I know that we can't do those. (If I could be allowed to help moderate I'd do it.)
