### ISSUE TITLE
Feature creep

### ISSUE THREAD

**Issue by themistocles-0** [olivierkes/manuskript#1236]
I feel that all the stuff tacked on makes the software to not be truly good, I think the editor portion alone if made to be more like atticus with documents and folders and having the tags (e.g: character, chapter, ideas, todo) for documents and folders with users being able to create their own tags would help users organize their stuff their own way rather than having way too much stuff strewn all about (having to do a lot of navigation to get to characters, chapter notes). It would be better to scale down how extremely specific the application is trying to be to authors but just have it be a way of organising your stuff with the export features present.

**Comment by FastusBellrune** [comment]
I think it's good like this for authors.

Also, if you want, you can ignore the World, Characters, and Plots sections and do everything in the editor. Just hide the navigation menu and create your Character or Item folders, and you're good.

If you want a program for taking notes and organizing them how you want, I suggest [Joplin](https://joplinapp.org/) instead of this. You can tag and organize your files however you want there.
