### ISSUE TITLE
Characters, Plots and Worlds are greyed out

### ISSUE THREAD

**Issue by kiwiG** [olivierkes/manuskript#1249]
(Running version 0.16.0 on Ubuntu 22.04.3 LTS)

Everything else seems okay, but I can't access Characters, Plots or Worlds. The windows and tabs are greyed out so I can't select tabs or type anything in (for example) Character Name.

**Comment by TheJackiMonster** [comment]
How did you install 0.16.0? Did you download and install the .deb file, did you update the snap package or did you install the flatpak?

**Comment by TheJackiMonster** [comment]
In case you installed the .deb package, you may try `sudo apt --fix-broken install` in case a dependency is missing.

In case you installed the snap package via the software store, you might need to adjust the permissions for Manuskript to work properly.

Otherwise I can't reproduce your issue with 0.16.0 in a VM. Maybe something else on your system is outdated though.

**Comment by kiwiG** [comment]
Thanks! Looks like a broken dependency. I installed from the .deb package and `sudo apt --fix-broken install` fixed it.
