### ISSUE TITLE
Markdown syntax highlighting

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#13]
Implement markdown syntax highlighting (at least a substantial enough subset)

**Comment by ParaplegicRacehorse** [comment]
May I suggest creating a markup highlighting plugin system instead of hardcoding for markup? I think markdown is fine and all, but I do all my writing in Asciidoc(tor) and would, of course, like appropriate highlighting. :smile:

I think, in the end, something along these lines will be easier for you to maintain in the core + your own favorite markup highlighting (txt2tags, right?) and encouraging others to contribute code for their favorites. True, not everyone is a programmer (definitely not me) but I think enough would take interest to create modules if the definition file format is simple enough.

**Comment by olivierkes** [comment]
Added in develop a new markdown syntax highlighter.

![image](https://user-images.githubusercontent.com/1192933/33431341-3f92309c-d5d4-11e7-919b-fa2ceff73385.png)

I also cleaned up the code so that it would be easier to create other highlighters, so that's still something possible for the future, but not yet :)
