### ISSUE TITLE
App crash when moving a step in Plots section

### ISSUE THREAD

**Issue by vinsifroid** [olivierkes/manuskript#134]
I'm running on Linux Mint 18.2 64-bit with manuskript-0.4.0 with a binary executable.
Steps to reproduce the bug : 
1. Add new plot in "Plots" section
2. Add two new steps for that plot
3. Try to move second step to first step to change their order by drag and drop

It's crash everytime i try it. No need to have two steps, it's crash not matter the number of steps by plot. I tried to change the importance of the plot but it doesn't change anything.
If need any additional information, feel free to ask.

**Comment by gedakc** [comment]
Thank you @vinsifroid for the report of this problem.

Using the manuskript-0.4.0 binary executable on GNU/Linux I was able to reproduce the issue.

Following are the error messages from the console
```
$ ./manuskript 
Running manuskript version 0.4.0.
Warning: failed to load translator for locale en_CA...
Loading: /home/gedakc/tmp/deleteme-2.msk
Detected file format version: 1. Zip: True.
Project /home/gedakc/tmp/deleteme-2.msk loaded.
Traceback (most recent call last):
  File "manuskript/ui/views/plotTreeView.py", line 96, in updateMaybe2
  File "manuskript/ui/views/plotTreeView.py", line 147, in updateItems
  File "manuskript/models/plotModel.py", line 44, in getSubPlotsByID
AttributeError: 'NoneType' object has no attribute 'text'
Fatal Python error: Aborted

Current thread 0x00007efd53b3d700 (most recent call first):
  File "manuskript/main.py", line 73 in launch
  File "manuskript/main.py", line 64 in run
  File "manuskript", line 13 in <module>
Aborted (core dumped)
```

I will look into this issue further.

**Comment by gedakc** [comment]
> I tried to change the importance of the plot but it doesn't change anything.

This problem with changing plot importance was fixed in the **develop** branch with the following commit:  [Fixes: add plot then choose new plot does not set importance slider ](https://github.com/olivierkes/manuskript/commit/3569f7892856d6ae2d0eb219a8a23d420c559e93)
and is planned for inclusion in the next official release of manuskript (0.5.0?).

The issue with the crash remains as initially described in the initial report.

**Comment by gedakc** [comment]
Thank you LaurentCR for adding to this report and not creating a new report.

>  I tried to change the importance of the plot but it doesn't change anything.

The issue with changing plot importance has been fixed in the **develop** branch.

> ...  it still crashes every time I try to move a step in any plot in the "Plots" section

The issue with the crash remains as described in the initial report.

**Comment by LeviOdom** [comment]
Just to add my two cents to the mix:  I'm running into the same issue on Windows 10 x64 running the Manuskript 0.4.0 executable.

```
Running manuskript version 0.4.0.
Warning: failed to load translator for locale en_US...
Loading: C:/Users/lodom/Google Drive/Writing/Manuskript Projects/American Wizards in Space.msk
Detected file format version: 1. Zip: True.
Project C:/Users/lodom/Google Drive/Writing/Manuskript Projects/American Wizards in Space.msk loaded.
Traceback (most recent call last):
  File "manuskript\ui\views\plotTreeView.py", line 96, in updateMaybe2
  File "manuskript\ui\views\plotTreeView.py", line 147, in updateItems
  File "manuskript\models\plotModel.py", line 44, in getSubPlotsByID
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by olivierkes** [comment]
Wow, this was quite boring to fix... Really hope this works.

Few other bugs fixed as well:

- when drag'n'dropping multiple items behavior could be unpredictable
- when updating name or order of subplot(s) then it would not refresh in the outline view
- when drag'n'dropping in Outline view from plot step to text item, summary was empty
- few other small things.

Also I enhanced a little bit the interface:

- `CTRL+Enter` to add a plot step
- Plot step is added under currently selected plot step, whereas before it was added at the end no atter what (though there is a bug I could fix that makes them both selected, instead of only the newly added one)
- `CTRL+Backspace` to remove selected plot step(s)
- Multiple plot steps can be deleted at once, whereas before it was strange.
- Moving selection of plot steps with arrow keys updates summary, whereas before you had to click

**Comment by gedakc** [comment]
Thank you @olivierkes for fixing this and a number of other issues.  I have confirmed that the steps listed in the first post of this issue now work correctly.

I noticed that you changed the milestone to 0.5.0.  I think this enhancement would be a good addition to the upcoming 0.5.0. release.
