### ISSUE TITLE
Manuskript fails to load last state of panels

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#14]
Sometimes manuskript fails to load the that state of panels like treeview or storyline.
Not a big deal but annoying.

**Comment by gedakc** [comment]
I performed a series of tests to learn more about the display behaviour of the window panes controlled by the tabs on the Right-Hand-Side (**RHS**) of the manukript window.

All testing was performed using the **develop** git branch on August 4, 2017 with head commit e971d7e167cd71060054c95a83bb6ee543247ac9.

# Initial Test Setup

1. Open an existing manuskript project with setting "_next time, automatically open last project_" enabled.
2. Select the _Redaction_ entry in the _Navigation_ pane.

# Perform for each RHS tab

1. Open Manuskript.
2. Set the state of one RHS tab to either **enabled** with pane **open**, or **disabled** with pane **closed**.
3. Close Manuskript.
4. Open Manuskript.
5. Note the visibility of the window pane and the RHS tabs.

# Test Results

Following are the results of testing window pane state and RHS tab state restoration.
Unexpected results are highlighted in **bold**.

|RHS Tab Name|Tab State on Close|Pane State on Close|Tab State on Open|Pane State on Open|
|------------|------------------|-------------------|-----------------|------------------|
|Cheatsheet  |Enabled           |Open               |Enabled          |Open              |
|Cheatsheet  |Disabled          |Closed             |Disabled         |Closed            |
|Search      |Enabled           |Open               |Enabled          |Open              |
|Search      |Disabled          |Closed             |Disabled         |Closed            |
|Navigation  |Enabled           |Open               |Enabled          |Open              |
|Navigation  |Disabled          |Closed             |**Enabled**      |**Open**          |
|Project tree|Enabled           |Open               |**Disabled**     |Open              |
|Project tree|Disabled          |Closed             |Disabled         |**Open**          |
|Metadata    |Enabled           |Open               |**Disabled**     |Open              |
|Metadata    |Disabled          |Closed             |Disabled         |**Open**          |
|Story line  |Enabled           |Open               |**Disabled**     |Open              |
|Story line  |Disabled          |Closed             |Disabled         |**Open**          |


# Result Analysis

Based on the results, it appears that only _Cheatsheet_ and _Search_ tabs and panes restore to the same state these were in at time of manuskript close.

_Navigation_, _Project tree_, _Metadata_, and _Story line_ panes appear to always be displayed when Manuskript is opened, regardless of state when manuskript closed.  Further the state of these RHS tab appears to always be disabled when Manuskript is opened.

It seems that for some of the RHS tabs, the link between the open/closed state of the pane is not tied to the enabled/disabled state of the RHS tab until the tab selection is clicked a couple of times.

# Next Steps

Because the _Cheatsheet_ and _Search_ tabs and panes appear to work correctly, the next logical step is to investigate to learn how these tabs are handled on manuskript project open and project close.

**Comment by olivierkes** [comment]
Well done !
