### ISSUE TITLE
add languagetool

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#142]
I have use LibreOffice with the languagetool Plugin for writing the last Years!

It's a great Help to make the writing better

**Comment by TheJackiMonster** [comment]
As mentioned in #745, there are already some good looking python bindings and there is an open http-api. So it should be able to integrate it even without difficult setup. ^^

**Comment by TheJackiMonster** [comment]
![Peek 2020-03-29 04-51](https://user-images.githubusercontent.com/13867397/77838959-fe9df380-7178-11ea-8bc8-e1fee5d01c00.gif)
Okay, I got this for basic grammar-correction and some stylistic information which can not be corrected via menu but manually. ^^'

I managed to implement it without to much messing around, I think. It checks if the module for Python ("language_check") is installed and uses it as new implementation of dictionaries. The other dictionaries had to get some new methods to make sure everything works without errors and such since LanguageTool is way more advanced than Enchant and others.

At the moment I have added three different error-visuals (underlining-colors) for "misspelling", "grammar / typographical" and "other". There is still much work to do, so that errors are all marked correct and this tool is still pretty slow. One thing I found out during testing is that the method to highlight the text is called more than once for the same text. So there is still much which can be optimited... ^^'
