### ISSUE TITLE
Feature suggestion: Typewriter scrolling.

### ISSUE THREAD

**Issue by vithiri** [olivierkes/manuskript#175]
For more comfortable writing, I'd like to propose adding typewriter scrolling, i.e. always centering the active line on the screen once reaching the middle of the screen. Please let me know if examples of the feature are needed, and I will track some down.

**Comment by olivierkes** [comment]
Good idea, thanks !

**Comment by hugo-id** [comment]
Any timeframe for this?

Currently using focuswriter for actual writing, and manuskript for everything else. Even implementing pagination would be enough. Always staring at the very bottom of the screen becomes oddly demoralising quickly.

**Comment by olivierkes** [comment]
What do you call pagination?

**Comment by olivierkes** [comment]
>Any timeframe for this?

It will be available in the develop branch in a day or two.

**Comment by olivierkes** [comment]
It's in develop. Please test and report any useful observations :)
(I'll close it for now since it is implemented, but you can re-open it if needed)

**Comment by vithiri** [comment]
That's exceptionally good news! I'll have a look at the dev branch as soon as possible.

**Comment by hugo-id** [comment]
Hey Olivier, downloaded and running developer branch, but I can't seem to find the option anywhere?

There's a real chance I'm either blind, or not actually running the developer branch, but I followed your incredibly well-made wiki so I believe it's simply a matter of me being unable to see the option.

And apologies for slow response, it seems like "pagination" is a term I have  made up..

[Pocket](https://getpocket.com/?ep=1) is an incredibly awesome article curation and various other things app (it's late and I already spent far too much time leaving feedback on a feature you already closed :smile: ). I can't find any other source on the internet so I'll just explain it here.. :sob: 

Right now we have an infinite "page". Imagining an actual typewriter, we're effectively using uncut paper, straight from the production line. We can just keep typing indefinitely, as we never have to worry about anything.

"Typewriter mode" ironically doesn't really do anything to make it more like a typewriter. Now, you still have an infinite page, but the metaphorical "typing mechanism" is located higher on the page.

"Pagination" makes it as if you are writing by hand on a page. You start at the top, move to the bottom, **then get a new page**. So instead of typing onto a theoretically infinitely long piece of paper, we're typing onto finite, limited pages. This means it's more like typing in a zoomed-out classical word processing application. This is may not be the greatest mode for typing, but it is definitely one of the best for quick scanning and more in-depth proof-reading.

Haha, wow, I clearly like the sight of my own writing far too much. Hopefully that makes sense to you!

**Comment by olivierkes** [comment]
Thanks @hugo-id, I get a better idea of what you mean. If typewriter mode is enough, I'll stick to that for now.

Option is in **Edit** > **Settings** > **Views** > **Text Editor** > **Cursor**

![image](https://user-images.githubusercontent.com/1192933/33441913-29e44602-d5f4-11e7-9c84-0501dfd147cd.png)

**Comment by koksalbasar** [comment]
Hi Oliver,

The Manuskript is the software that I look for. Typewriter scrolling is very good idea for the focused writing. So, what do you think about typewriter sound effects?  I use FocusWriter for this feature. Using computer as a old school typewriter is realy big fun. 

If you plan to add this feature I (maybe many others) will not need any other software.
