### ISSUE TITLE
Select Color dialog open below Manuskript window

### ISSUE THREAD

**Issue by vmpajares** [olivierkes/manuskript#20]
When I created a new Character and I click the color to change it manuskript opens a Select Color Dialog. This windows opens below the Manuskript main window and not over it.

By the way, the dialog is called "Select Color", and didn't appear in the translation file to change it to "Elige un Color". I don't know if it is a hardcoded name or is a bug with my local QT installation.

**Comment by src-r-r** [comment]
What OS are you using?

**Comment by gedakc** [comment]
I am unable to replicate this issue using Manuskript 0.7.0 on Windows XP, Windows 10, Kubuntu 16.04, and Fedora 25.  This leads me to believe the issue has been fixed since it was first reported.

Closing this issue as invalid as I don't know when it was fixed.

If the problem recurs with the latest manuskript then we can re-open this issue.
