### ISSUE TITLE
Global search and replace

### ISSUE THREAD

**Issue by darrelwright** [olivierkes/manuskript#209]
I have seen this feature had been submitted. But does not appear to work in version 0.5.0?

Darrel

**Comment by gedakc** [comment]
As you discovered global search and replace was not implemented in version 0.5.0.  If you look at the prior issue #145 report you will see that it is still open.  If you have additional comments then please add to the existing issue report rather than creating a new report.

Closing this report as a duplicate of issue #145.

**Comment by olivierkes** [comment]
(Adding the `duplicate` label, because I'm using [github_changelog_generator](https://github.com/skywinder/github-changelog-generator) and it ignores issues labeled `duplicate`).

**Comment by gedakc** [comment]
Thanks for the tip @olivierkes.  :+1:
