### ISSUE TITLE
System Restore Changed my .msk File

### ISSUE THREAD

**Issue by OlsonAC1** [olivierkes/manuskript#217]
I used a System Restore Point on Win 8.1 after saving my file and closing Manuskript. The System Restore menu did not say that the Manuskript program would be affected by the Restore. I reopened the file after the Restore and the text changes I made (after the Restore Point was created) were reverted. And not just text, a new Outline entry I had created today was also gone. I am using Manuskript version 0.5.0. The file was kept on the same drive that was restored.

**Comment by olivierkes** [comment]
Hi @OlsonAC1,
Sorry to hear that, hope you did not lose to much work because of that..!
I don't know anything about System Restore, just quickly read the wikipedia entry to get an idea.

Few questions:

- How do you know which files are restored or not when you do a restore?
- Were you saving [in one file, or in a folder](http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/)?
- Is this something you could reproduce?

My guess would be that windows simply restored the file to the old version. If that's the case, I don't think manuskript can do anything about it, right? Or maybe windows thought this `*.msk` was some kind of system file, and we can tell the system that it's not?

Anyway, thanks for reporting!

**Comment by OlsonAC1** [comment]
I'm no expert on System Restore either, so I don't know how it decides which files to change. My guess would be files in "Programs", etc. named folders. My .msk was in my Google Drive folder, and other files in that folder do not appear to have reverted. My entire story is in a single file. I will have more time to mess with it again tomorrow. I should be able to reproduce it. Is there anything you'd like me to test when I do?

**Comment by gedakc** [comment]
> @olivierkes: My guess would be that windows simply restored the file to the old version

I think the issue you encountered is as @olivierkes indicated.

This would be similar to if you had an older backup of the .msk file on a USB flash drive and you copied the older .msk overtop of the newer version on your hard drive.  As far as I know there is nothing that manuskript or any other application can do if you overwrite a file.

**Comment by OlsonAC1** [comment]
@gedakc I wasn't expecting Manuskript to be able to fix it. I was simply reporting the occurrence. As I said, the other files in my Google Drive folder were not affected by the Restore Point.

**Comment by olivierkes** [comment]
>Is there anything you'd like me to test when I do?

I don't know if this is useful, but here are a few things *I* would try out of curiosity. If you feel like trying some or others, please do :)

- Save a project in open folder format (not single file format), and see if it is reverted
- Save a project in single file format, and change the name to "project.zip" to see if it is reverted (and have a modified zip file next to it to compare)
- Be extra sure that other files in the same folder are not reverted
- Be sure that there is not an option somewhere that you checked or whatever and that caused your project to be restored, and not other files

That could give us an idea on how System Restore works, and maybe confirm that manuskript cannot do anything about it.

**Comment by OlsonAC1** [comment]
@olivierkes 
Before restoring (and after backing everything up on an external drive), I copied my .msk file and zipped it, then made another copy and renamed it to be a .zip. I opened my .msk and changed the settings to save as a folder. I also opened a Word .docx, added "TEST" to the top of the doc, and renamed it to say "+ TEST".  (Sorry, I realized after the fact that you probably wanted a zip file to be literally "project.zip".)

Here is a screenshot of my folder before the Restore:
![before restore files](https://user-images.githubusercontent.com/18723027/32919851-3f34ac90-caf5-11e7-8f31-df3cf0c41d3c.png)

And here is after:
![after restore files](https://user-images.githubusercontent.com/18723027/32919855-424d247a-caf5-11e7-95b1-0f1af220c643.png)

The .docx file is intact, as is the file name change. (It still says "TEST" inside.) But as you can see, the new Manuskript files are missing. The remaining .msk has been renamed to its original file name from before the Restore Point was created.
The folder-version save of the msk seems intact (it has one less scene file than the .msk file because I removed one), but as any file that I try to open manually either crashes the program or opens a blank file, I can't see the content. How do you open folder-version saves when the program doesn't know to open it on startup?

As for options in the Restore process, there is nothing about individual files, only drives and Restore Points, because it is not supposed to affect other files at all. And once again, Windows did not say Manuskript would be affected.

**Comment by olivierkes** [comment]
Thank you very much for those details.

> My guess for the cause of all this is there's something about how .msk files are created that tag them as system files to Windows.

.msk files really are just zip files with the .msk extension. They're no difference in terms of content than any zip file. I guess now that they are treated as system files because they are not registered. I don't know how that works in windows, but there must be some kind of "file association" settings, and maybe if/when we provide a proper manuskript installer on windows, we can associate .msk files with manuskript, and they would not be treated as sysstem files anymore.

>The folder-version save of the msk seems intact (it has one less scene file than the .msk file because I removed one), but as any file that I try to open manually either crashes the program or opens a blank file, I can't see the content. How do you open folder-version saves when the program doesn't know to open it on startup?

The folder-version must be associated with a .msk plain text file that contains the version number:

```python
    project/*    # ← folder
    project.msk  # ← content is just: 1
```

So if that file is missing (reverted?) you can juste create a plain text file with the same name and write `1` inside, and open it. (I realize that this is really not ideal, will have to improve that, and I'm open to suggestions on how to open folders.)

If you still cannot open it, can you please tell me the error message you get?

**Comment by gedakc** [comment]
> @olivierkes: I guess now that they are treated as system files because they are not registered. I don't know how that works in windows, but there must be some kind of "file association" settings, and maybe if/when we provide a proper manuskript installer on windows, we can associate .msk files with manuskript, and they would not be treated as sysstem files anymore.

I'm not sure, but I think these "file associations" are similar to MIME types and are "registered" with the operating system.

To support these "file associations" we probably need to enhance manuskript to take a `filename.msk` as a parameter so that it will open the file in manuskript.  For example `manuskript filename.msk` on the command line, or from a file manager a user double-clicks `filename.msk`.

**Comment by olivierkes** [comment]
Good point, created an issue to remember.

For now, @OlsonAC1, if you were willing to do more tests we could test that hypothesis:

- Associate manuskript with *.msk files (in GNU/Linux I'd do something like: `right-click > open with > remember file association`)
- Check: if you double click an msk file, manuskript should launch (though the specific project will not open as that is not implemented yet)
- Create a restore point
- Modify .msk a project
- Revert
- Check if reverted

**Comment by OlsonAC1** [comment]
@olivierkes 

>.msk files really are just zip files with the .msk extension.
I said nothing earlier about the file I renamed from .msk to .zip because I thought I originally misunderstood you. My computer was not able to unzip that file. My freeware program 7zip said it it not an archive, and my in-house Windows program says it's empty.

> The folder-version must be associated with a .msk plain text file
I did not realize that Manuskript would use the same .msk file for saving to a single file as a folder-version. The .msk reverted while the folder files did not. When I opened the reverted .msk, I saw a reverted story rather than what was in the folder. 
For my own sake, I tried to figure out how I would have been able to open the folder version from a reverted .msk. This is what I came up with:
1. Move folder elsewhere.
2. Open reverted .msk and tell it to save to folder. Save and exit.
3. Replace newly created folder with old folder.

Things are busy this week, so I may get to more testing today or next week.

**Comment by OlsonAC1** [comment]
I did the 2nd restore test (after associating .msk with program, etc.) and the .msk still reverted, while the folder did not. So I guess it should be encouraged that users save to a folder-version as the default when possible, as that seems to be immune to this problem.
