### ISSUE TITLE
How to use RTL (right-to-left) languages? (Pasting Hebrew Text)

### ISSUE THREAD

**Issue by darrelwright** [olivierkes/manuskript#218]
How do I paste Hebrew text into Manuskript? When I paste " הלל" into a scene everything following becomes right-to-left justified. The only method I have found is to enter some text, then a double quote then some more text. I can then past the Hebrew characters between the quotes as shown above. This makes it very difficult. Is there something I am missing?

**Comment by olivierkes** [comment]
I saw an interresting blog post from a guy who uses manuskript in Israel: https://wordpress.com/read/blogs/96325275/posts/2059 (I used google translate to read). We had a small exchange in the end.

Interresting thing is: manuskript seems to be the only free software he tried that handls RTL (right to left) writing out of the box. My guess is that Qt detects if the first character of a paragraph is from LTR or RTL script, and sets the direction accordingly. So as long as there are some english characters first on a line, then it will work. You can type in english, then paste the hebrew, and — though the cursor is at the end of the word so on the left of it — continue typing in english. No need to type double quote, come back and paste. But there would be a problem if hebrew characters need to be at the beginning of the line.

Do you think it's really a big deal? I would need to read more about that.

**Comment by darrelwright** [comment]
This is still an issue. When I enter English text "able ", then paste a Hebrew word, the word order is changed from LTR to RTL for anything else being entered. The only way it works to enter English, leave a couple of spaces, enter some more English, then move the cursor back to the spaces and paste the Hebrew word. Then I can continue typing after the last English entry.

For me this is a pretty big deal since I work on a lot with Hebrew/Greek/English words. Can we address anything here? Thanks!

**Comment by olivierkes** [comment]
I really want to address it, but I don't understand the issue. Look here:

![hebrew](https://user-images.githubusercontent.com/1192933/33599364-3dee3ef4-d9a6-11e7-97b0-dc7c8b7647f0.gif)

I simply: 

- ‎Type in english
- Paste hebrew (but you could also switch keyboard layout and type in unicode hebrew) [cursor goes to the left of the word because recognized as RTL]
- Keep typing in english [cursor automatically jumps to the right, because recognized as LTR]

And as you can see from my back-selecting, the hebrew word *is* RTL. (When I'm back-selecting, I'm simply holding Shift and pressing *only* the left arrow keys. It switches to the left of הלל and moves right, but I keep pressing left.)

Yet I don't observe any word order changed.

If I misunderstood you, please describe again your issue, and sorry for being slow :)

**Comment by darrelwright** [comment]
Hi Olivier,
You're not slow. It is always fun and challenging to have two people from different countries and primary languages to fully understand one another! :)

I just had an "Ah hah!" moment! I had never tried to just continue typing English after pasting the Hebrew word. I had been trying to use the arrow keys to move to right side of the word and that was not working. Fascinating! You are correct. It works just like you designed it! My oh My! Thank you for helping to clean up my understanding!

Now I can get on with my writing. Have an awesome day!

Darrel

**Comment by olivierkes** [comment]
I'm glad it works :)
Have a great day and inspired writing!
