### ISSUE TITLE
Welcome windows on OS X: single click instead of double click

### ISSUE THREAD

**Issue by olivierkes** [olivierkes/manuskript#23]
On OS X, items on welcome windows templates list need to be double-clicked to be activated.

Change that to single-click (as in settings, or any place else).

**Comment by gedakc** [comment]
@olivierkes is this now fixed in the **develop** branch as a result of the changes that fix issue #44?

I think the change from _itemActivated_ to _itemClicked_ seems to have fixed the issue with the welcome windows templates.

The manuskript source code does contain an _itemActivated_ call in two other locations:

[manuskript/ui/editors/completer.py - line 24](https://github.com/olivierkes/manuskript/blob/develop/manuskript/ui/editors/completer.py#L24)
[manuskript/ui/cheatSheet.py - line 32](https://github.com/olivierkes/manuskript/blob/develop/manuskript/ui/cheatSheet.py#L32)

I do not have OS X to test with, but on my Kubuntu 16.04 system with the **develop** branch I am able to use a single-click to activate the welcome windows templates.

**Comment by olivierkes** [comment]
Good point, thanks.
I changed the signal in `completer.py`, and kepp them both in `cheatSheet.py`. I guess it should work on any system, though if someone with OS X or Gnome could test, that would be great.

**Comment by gedakc** [comment]
Using Fedora 25 with GNOME I confirmed that welcome templates only need a single click.  :-)
