### ISSUE TITLE
[Feature suggestion] Notes section for full project

### ISSUE THREAD

**Issue by thoronaug** [olivierkes/manuskript#247]
I miss a "Notes" section for the whole project. 
Sometimes you have some ideas about the project (like "Introduce a new character who always replies the main character" or "Study de possibility of using a first person narrator in the introduction") and it would be great to have a common place where to write them down.

**Comment by gedakc** [comment]
Thanks @thoronaug for helping to improve manuskript.

Currently you can create a folder or a text, rename it, and uncheck the **Compile** metadata property so that is is excluded when compiling/exporting the document.

![manuskript-with-notes-folder-text](https://user-images.githubusercontent.com/10405019/33458327-0fe6bf66-d5e3-11e7-9e5a-8549c749435d.png)

Does this work for you for keeping notes?
Or did you have something else in mind?

**Comment by thoronaug** [comment]
Yeah, I think this will do the trick. It's even better than a single "Notes" field.

Thank you so much!

**Comment by olivierkes** [comment]
You can even use a custom icon if you feel like it ;)

![image](https://user-images.githubusercontent.com/1192933/33553192-07a3bc7e-d8f8-11e7-958b-e272a9bd96ef.png)

**Comment by thoronaug** [comment]
It's perfect. Thanks @olivierkes :) 👍
