### ISSUE TITLE
saving error

### ISSUE THREAD

**Issue by bartart3d** [olivierkes/manuskript#274]
Hi all,
running Manuskript 0.6.0-1, installed with a .deb file, 64 bit Ubuntu 17.10 .

For testing purposes I copied the text of an old unfinished 30 page long story, and pasted it into Manuskript. I saved the file with the option to have seperate files, not in a single file. 

Then I started to split the text into several sections, for each scene a new text. 

But then ubuntu started to throw error messages, that Manuskript had crashed, while Manuskript still showed on the screen. I pressed save (to be surely sure), exited, then restarted Manuskript and opened the file to see that all changes had been lost. The first save had succeeded, the text was there, but all changes after that were gone.

I guess the internals, or backend of Manuskript indeed had crashed, but that the GUI part of the program still ran. 

I looked into the error message provided by Ubuntu's crash report and I came up with this error:
manuskript crashed with lxml.etree.XMLSyntaxError in lxml.etree._raiseParseError(): internal error: Huge input lookup, line1, column 10334295 .

I have no clue what it means, (Maybe the text file was to large for one single text?) but I hope you developers are helped with this error message to make Manuskript more stable :-)

grtz,
Bart

**Comment by gedakc** [comment]
Thank you Bart for your interest in Manuskript.

Could you try invoking manuskript from a terminal window (**Ctrl+Alt+T**), repeating the steps that demonstrate the problem, and then copy the console messages from the terminal and paste these in this issue report?

This would go a long way towards helping us to identify the cause of the issue.

**Comment by olivierkes** [comment]
Thanks Bart,

My guess is that the file you copied from, and manuskript, do not use the same EndOfLine character, so that what you pasted was imported as one *very* long line (`internal error: Huge input lookup, line1, column 10334295`, 1 line, 10M characters!). 

So in addition to what @gedakc asked (which would help us locate the part of manuskript where the problem happens), could tell me if you saw something that would support my hypothesis? Was it all pasted as one long line? Or could you post here the document (if its not too sensible of course)?

Also, you could try, instead of copy/pasting, to import your document (File > Import). For that you need to have pandoc installed. And tell us if it behave the same.

Thank you very much, this will really help us fix a nasty bug!

;)

**Comment by bartart3d** [comment]
Aha, weird to say, but glad to report that the error happened finally :-)

Here is the traceback:

Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/mainWindow.py", line 717, in saveDatas
    r = loadSave.saveProject()  # version=0
  File "/usr/share/manuskript/manuskript/loadSave.py", line 21, in saveProject
    return v1.saveProject()
  File "/usr/share/manuskript/manuskript/load_save/version_1.py", line 260, in saveProject
    files.append(("revisions.xml", mdl.saveToXML()))
  File "/usr/share/manuskript/manuskript/models/outlineModel.py", line 524, in saveToXML
    root = ET.XML(self.rootItem.toXML())
  File "src/lxml/etree.pyx", line 3206, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1759, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1125, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: internal error: Huge input lookup, line 1, column 10276749


grtz,
Bart

**Comment by olivierkes** [comment]
Thank you very much.
I'm not sure why the huge input lookup happens, but this seems to be a fix along the line of https://github.com/larrys/shareplum/commit/717c9e3157614b58b2d8145c4e11ce428b37114a

I'll have to check that there are no drawbacks, and that it's applicable in our situation, and then I could correct it.

Thanks again for reporting.

**Comment by TheJackiMonster** [comment]
Okay, so I enabled the flag to parse huge XML files now ( [19cbe7f](https://github.com/olivierkes/manuskript/commit/19cbe7fdf65737275bbdacd4eb1939d89fc952ef) ) since at least from my look at it issues in libxml2 regarding it were [all closed](https://gitlab.gnome.org/GNOME/libxml2/-/issues/?search=XML_PARSE_HUGE&sort=created_date&state=closed&first_page_size=20).

I assume this change should fix the original issue. Obviously there is always a chance that other vulnerabilities in the future may be caused by using this option (when you try to open/load or save an XML file with malicious contents exploiting some issue in libxml2). However I don't think it's a very likely attack scheme for our use case given how small the user base of Manuskript is in comparison to any big word processor software. Also I don't think it's very likely to open/load or save projects which have been received by others because Manuskript is a software specifically designed for authors with export functionality to share parts of their work in a selected format.

So I'm closing this issue.
