### ISSUE TITLE
Install on MacOsX failed

### ISSUE THREAD

**Issue by cfrancois7** [olivierkes/manuskript#282]
Dear everyone,

I tried to install Manuskript on my Mac, but I failed. See the error message:

```
$ /Users/myName/Downloads/manuskript/manuskript ; exit;
[32512] Error loading Python lib '/Users/myName/Downloads/manuskript/Python': dlopen: dlopen(/Users/myName/Downloads/manuskript/Python, 10): Symbol not found: _clock_getres
  Referenced from: /Users/myName/Downloads/manuskript/Python (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/myName/Downloads/manuskript/Python
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
```

It seems the builder looks for the `python`directory inside the manuskript repository, but there is no `python` dir inside.

**Comment by gedakc** [comment]
Which version of manuskript are you using (0.6.0 is the latest)?

Are you [running from source code on OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X), or did you [install from the PyInstaller binary package](http://www.theologeek.ch/manuskript/download/), for example `manuskript-0.6.0-osx.zip`?

**Comment by cfrancois7** [comment]
I followed the instruction from "http://www.theologeek.ch/manuskript/download/".
It was `manuskript-0.6.0-osx.zip`.

version of MacOsX: 10.11.6 (El Capitan)

**Comment by gedakc** [comment]
The current Mac OS X PyInstaller package is automatically built using [Travis CI](https://travis-ci.org/).  It appears that the current [default for Travis CI is Mac OS X 10.12.6](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version).

I suspect that the `manuskript-0.6.0-osx.zip` PyInstaller package does not work on your computer because you are running an older version of Mac OS X.

@cfrancois7, another option you might consider is to [Run Manuskript from Source Code on Mac OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X).


### Question for @olivierkes and/or @katafrakt:

Do you think it would be feasible to automatically build the Mac OS X PyInstaller package using an older version such as **OS X 10.10** which is listed as supported by Travis CI?

To enable such a change I think we would need to add a line with [`osx_image: xcode6.4`](https://docs.travis-ci.com/user/reference/osx/#OS-X-Version) to the `.travis.yml` file.

PyInstaller suggests using the oldest version of an operating system in order to support as many OS versions as possible.  See [PyInstaller - Making Mac OS X apps Forward-Compatible](https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible).

**Comment by katafrakt** [comment]
@cfrancois7 Sorry for the problem with Manuskript package for El Capitan. Could you perhaps try [this experimantal release](https://github.com/katafrakt/manuskript/releases/download/0.6.1/manuskript-0.6.1-osx.zip) and tell us if it works?

@gedakc 6.4 is tricky, because Enchant refuses to compile with it (see: https://travis-ci.org/katafrakt/manuskript/builds/323261127#L1879), however next one (7.3) builds fine and works for me. Let's see if it solves the issue for @cfrancois7 and then we can use this image, I think.

**Comment by cfrancois7** [comment]
@katafrakt: the experimental release works fine. Thank you.

**Comment by gedakc** [comment]
Thanks @katafrakt for building a manuskript package based on `osx_image: xcode7.3` and thanks @cfrancois7 for testing to confirm it works on Mac OS X 10.11.6 El Capitan.

@katafrakt would you be able to create a PR for @olivierkes to review and commit?

You might also include in the commit comment that  `osx_image: xcode6.4` would not work because Enchant refuses to compile with it.

**Comment by cfrancois7** [comment]
It works well on Sierra too. I upgraded my OS this morning.

**Comment by gedakc** [comment]
Thanks @katafrakt for the patch, and thank you @cfrancois7 for testing.

I am closing this issue because PR #287 has been merged into the **develop** branch.  This enhancement is planned for inclusion in the upcoming 0.7.0 release.
