### ISSUE TITLE
[MacOs Sierra] The edition menu doesn't work

### ISSUE THREAD

**Issue by cfrancois7** [olivierkes/manuskript#286]
The edition through the edition menu has no effect on the text. Also, the shortcut CMD+key or Ctrl+Key has no effect too.

<img width="385" alt="capture d ecran 2018-01-01 a 20 21 15" src="https://user-images.githubusercontent.com/11422336/34470511-ea509d9e-ef32-11e7-9bdb-5421bb43d6d2.png">

Version: 0.6.1
MacOS version : 10.13.2

See also https://github.com/olivierkes/manuskript/issues/285 that is related.

**Comment by gedakc** [comment]
This bug is a duplicate of issue #250 which is a duplicate of issue #59. The format buttons have been removed from the git **develop** branch in preparation for the next release of manuskript (0.7.0).

@cfrancois7 if you wish to try the **develop** branch then see [Run Manuskript from Source Code on Mac OS X](https://github.com/olivierkes/manuskript/wiki/Run-manuskript-on-OS-X)
