### ISSUE TITLE
proposal: get a link between the notes/reference and the text

### ISSUE THREAD

**Issue by cfrancois7** [olivierkes/manuskript#295]
I'm used to write with some footnotes. It is interesting to put some commentaries, something to develop or change later, or just because it is a real note of the final version.
It could be nice if we could produce a link inside the text and the notes/references when it is required.
It is quite easy to deal with it in LateX, but currently Manuskript does not propose this kind of features.
Do you think it is something you are interested to develop?

**Comment by olivierkes** [comment]
Not sure I understand what you need. What kind of link would you like? The note/reference field is already linked to the text (since when you change the text, the note/reference changes).  Is what you ask is the possibility to link to a specific place in the text? Like a comment in LibreOffice?

For now, you can have both footnotes and comments:

![image](https://user-images.githubusercontent.com/1192933/34893018-b6cb9a80-f7db-11e7-98bd-02545d4f44df.png)

I use that feature a lot when writing, to annotate places, keep alternate version of a sentence just in case, or anything.

**Comment by bartart3d** [comment]
I started writing in LibreOffice and made extensive use of comments to highlight and specify problems or things to change. 
As an extra plus in LibreOffice it's easy to navigate through all the comments using the navigator when revising the document. In other words, glad to see comments being possible, but I'd love to see navigating from comment to comment being possible in Manuskript too, if that isn't possible yet (I havent discovered it so far).

**Comment by TheJackiMonster** [comment]
I suggest reopening this issue requesting an additional navigation of comments in the document because the question of the OP seems to be answered.
