### ISSUE TITLE
Show character count progress indicator

### ISSUE THREAD

**Issue by lechbaczynski** [olivierkes/manuskript#334]
Feature: Show characters (with spaces) count for the whole text, here:

![obraz](https://user-images.githubusercontent.com/1127623/37926701-519350ea-3138-11e8-8ddd-3c646631a354.png)

**Comment by gedakc** [comment]
Thank you @lechbaczynski for your interest in Manuskript.  I noticed you also provided a PR.

Normally publishers, writers, and sometimes readers are interested in the word counts for works of fiction and non-fiction.  However in my experience I have not encountered a situation where the character count is important.

What is the purpose of adding character count, and who uses it?

One reason I ask is because Manuskript has been criticised in the past for being too cluttered.  We are trying to keep distractions to a minimum so that writers can focus on creating their work.  That is why I am questioning the need for a character count statistic in the editor.

Regards,
Curtis

**Comment by lechbaczynski** [comment]
For most of (over 90% I suppose) of writing contests  - short story contests, and also some novel contests, etc., in Poland there is a limit in the rules, given in characters count. 
like for example 10.000 chars including spaces, or 27.000. Sometimes there is also a minimum char count (incl. spaces) stated in the rules.

See some examples:

"znaków" - means characters
"konkurs" - competition
"tys." - thousands
"opowiadanie" - short story

![obraz](https://user-images.githubusercontent.com/1127623/38460182-365efc30-3ab5-11e8-8cd3-e8020ad06df7.png)



The same for some novels ("powieść") contests:

![obraz](https://user-images.githubusercontent.com/1127623/38460217-a8259bd0-3ab5-11e8-9ffc-9981772ebbae.png)

**Comment by lechbaczynski** [comment]
Real life example - yesterday I finished writing short story for competition, 
the limit was 10.000 chars including spaces.
I wrote in Manuskript run form sources form my forked github repo - with char count feature.
The feature was very useful, see the sum of characters in all scenes on the screenshot:


![obraz](https://user-images.githubusercontent.com/1127623/38460406-7489a9ac-3ab9-11e8-85ce-ffb7f7b35393.png)

**Comment by lechbaczynski** [comment]
Also, other program have it
minimalistic Focus Writer, see:

http://cdn.osxdaily.com/wp-content/uploads/2011/09/focuswriter-theme.jpg

and even Scrivener:
https://www.literatureandlatte.com/assets/image/scrivener/features/windows/win-1-binder-editor-inspector.png

**Comment by gedakc** [comment]
Thank you @lechbaczynski for the additional information regarding the use of character counts in writing competitions.  It would seem that a character count would be a useful addition to Manuskript.

I will post some suggestions for enhancement in the PR you created.

**Comment by deerainw** [comment]
In some languages, such as Chinese and Japanese, we can't find even one space in a long paragraph in most cases.
If I paste a very long Chinese article which contains 10 long paragraph into manuskript, the info ` 10 words` on status bar is useless.
