### ISSUE TITLE
Enable/Disable POV-Option for Characters

### ISSUE THREAD

**Issue by ScullyBlue** [olivierkes/manuskript#335]
In my actual project, I see, that the list of characters can get ... long. But not all characters get a own POV in story. It would be very nice, if I could disable or enable for each character that he stands in the List of POV-Characters or not.

**Comment by TheJackiMonster** [comment]
I think this shouldn't be too complicated, so I will try to add this next. I have a higher amount of characters too but the most of them get an own POV. But maybe in the future I can make use of it. ^^

**Comment by TheJackiMonster** [comment]
Okay, I looked into the code and this request is probably more difficult than I thought to implement. It would require a separate model of all enabled characters next to the model of all characters and they have to be synchronized too. I think it's better to improve searching in such sort of selections for specific characters rather than filtering them. ^^'
So for the moment it looks like we have to deal with all characters for now. Maybe some alphabetic ordering (#321) would already help in the selection too.

**Comment by obw** [comment]
@TheJackiMonster A searchable POV would be a Dream, My biggest project where I use Manuskript has about 100 Characters, still growing;).

When I ever done with this monster of an Idea there will be 10.000+ Characters.

**Comment by TheJackiMonster** [comment]
I didn't implement a full search now but I got to fix the original issue as mentioned above. So a POV can be disabled for a character individually. It was easier as I thought yesterday because Qt had some classes and functions already in mind for such a filtering task. ^^

**Comment by TheJackiMonster** [comment]
@obw It's probably good to open the searchable POV as new issue. So I would close this one for now.
