### ISSUE TITLE
[Feature request] References in characters' bios

### ISSUE THREAD

**Issue by valodiadeseynes** [olivierkes/manuskript#347]
Hello,

I think it would be very helpful to be allowed to reference world entries and other characters in each character's basic info, summary, notes and detailed info tabs.

As far as I know, this isn't possible yet.

Thank you and great work!

**Comment by caseyjp11** [comment]
I'll leave an emphatic +1 to this because as the application stands, it can't be easily used in a sci-fi/epic fantasy setting for writing as "world building" is a huge part of the process.

An author trying to keep track of multiple characters across multiple worlds, needing cross-referencing and such will be frustrated by the limitations imposed by the manuskript software at this point.

In my own case, while I am testing the app (I really like the look and feel, it won't work for MY workflow.  By switching my projects to LyX and using Cherrytree for the "binder" if you will, I can get the work done much more efficiently.

**Comment by BlackXanthus** [comment]
(Suggestion) It would seem to me that this can perhaps be done by adding references into Detailed Info. Detailed Info already shows up on the CheatSheet, and if those could be references, it would enable interconnectivity.

**Comment by TheJackiMonster** [comment]
I think this issue can be closed. I can definitely add references with Ctrl+Space to the bios of my characters.
