### ISSUE TITLE
Develop Branch Crashes in Outline View

### ISSUE THREAD

**Issue by rcrx** [olivierkes/manuskript#355]
Program crashes when using `shift` or `ctrl` to select multiple items in the Outline view of the Develop version. Works fine, however, in the project tree of Editor mode.

**Comment by gedakc** [comment]
I have confirmed this issue by `shift` selecting multiple items in the **Outline** pane.

**Comment by RiderExMachina** [comment]
Confirmed happening in version 0.7.0 as well. Same error message.

**Comment by RiderExMachina** [comment]
@gedakc 
I've updated the PR to be an actual fix. It doesn't tiptoe around the issue (as we discussed in the PR).

**Comment by gedakc** [comment]
Thank you @RiderExMachina for the updated PR to address this issue.

I tested creating, deleting, and multiple-selecting world items and outline items.  In each case this PR enabled manuskript to function properly.  No regressions were found.  As such I have merged the PR into the **develop** branch for inclusion in the next release of Manuskript.

Note that I initially merged the patch into my own fork of manuskript.  I have since corrected that and merged the patch into @olivierkes manuskript git repo.
