### ISSUE TITLE
[feature request] Scene Search

### ISSUE THREAD

**Issue by nephlm** [olivierkes/manuskript#376]
The search pane will show you all the scenes that the term, but there are some drill down use cases that aren't well supported. 

To put it in user story terms: 

As a writer who overuses the word 'could' (or whatever), while revising I want to be able to search in the scene for that specific term and have a way of finding where in the potentially long scene that word or phrase appears.  This may be by highlighting the phrase in the text or having a prev/next(F3) button that will jump to the next instance.

**Comment by madeonearth** [comment]
I second this request!
Highlighting the search phrase is standard for every text editor. 
Notepad does it.

When I enter a search criteria e.g. ‘Lord’ all Chapters containing ‘Lord’ are listed below.
You are beeing pointed to the according scene.The search for ‘Lord’ is not visually reflected in the editor though.
It takes for ever finding the occurance in the text manually.

Instead of highlighting the phrase ‘Lord’ the spellcheck is beeing activated and does its thing even though spellchecking was deactivated from the main menu. 
Is this a bug? 
Maybe Manuscript is supposed to highlight the search phrase but instead underlines with the spellchecker ...

Manuscript seems to ignore the setting for the spellchecker once you used search or cheat sheet!!

**Comment by qantravon** [comment]
I'll third this. Definitely need to be able to see where the specific instances of found terms are at the editor level, not just at the "scene" level.
