### ISSUE TITLE
"Corrupted" settings and impossibility to start

### ISSUE THREAD

**Issue by TeebObeeT** [olivierkes/manuskript#377]
_Environment_: Windows 10
_User_: Simple user, no admin rights
_Version_: 0.7.0

**What happened**:
1. Unzipped Manuskript in Download folder
1. "Play" with it, in settings, change to language = french and "open last project"
1. Save project
1. Close Manuskript
1.  Try to reopen:

```
Debug: Web rendering engine used: QWebView
Running manuskript version 0.7.0.
Found translation in settings: C:\Users\az02094\Downloads\manuskript-0.7.0-win32\manuskript\i18n\manuskript_fr.qm
Loaded translation: C:\Users\az02094\Downloads\manuskript-0.7.0-win32\manuskript\i18n\manuskript_fr.qm.
Traceback (most recent call last):
File “manuskript\ui\welcome.py”, line 74, in showEvent
File “manuskript\mainWindow.py”, line 557, in loadProject
TypeError: QObject.tr(str, str disambiguation=None, int n=-1): ‘importance’ is not a valid keyword argument
```
6. Found that settings were in project, therefore deleted my playground project called plop
```
Debug: Web rendering engine used: QWebView
Running manuskript version 0.7.0.
Found translation in settings: C:\Users\az02094\Downloads\manuskript-0.7.0-win32\manuskript\i18n\manuskript_fr.qm
Loaded translation: C:\Users\az02094\Downloads\manuskript-0.7.0-win32\manuskript\i18n\manuskript_fr.qm.
The file C:/Users/az02094/Desktop/plop.msk does not exist. Try again.
Traceback (most recent call last):
File “manuskript\ui\welcome.py”, line 74, in showEvent
File “manuskript\mainWindow.py”, line 557, in loadProject
TypeError: QObject.tr(str, str disambiguation=None, int n=-1): ‘importance’ is not a valid keyword argument
```
7. moving the folder to Program Files (x86) with admin user
8. try again, no effect

___

**Solution to get out of the situation** 
*(Not a solution per se, but a workaround if someone get in the same trouble)*:
1. Find the sample project book-of-acts.msk 
1. Click on it and select Manuskript.exe as associated program
1. Remove the check "open last project next time" - just in case ;)

**Comment by gedakc** [comment]
On Windows another work-around / way to clear out all the Manusrkipt settings is to start `regedit.exe` and delete the `HKCU/Software/manuskript/manuskript` registry hive entry.

**Comment by RiderExMachina** [comment]
@TeebObeeT I'm not having this issue with the main release of 0.7.0. Are you using the develop version "running from source code?"

**Comment by RiderExMachina** [comment]
@gedakc 

I've found the issue that causes this and can "turn it off and turn it back on," but I don't know if I can just blatantly remove the flag itself from the code (obviously the programmer put it in there for their own reasons). I've done a little bit of research regarding the code they call and haven't found anything substantial (particularly for PyQt--the official documentation is for C/C++). So that gives us three options:

1. Talk to to author of the code (if possible)
2. Remove the offending flags that cause this issue (and add a comment just below the line with the flag)
3. Add a flag in the call

Neither 2 nor 3 bring up an error message (like I assume they're supposed to), so while they'll resolve the issue, it won't act as expected. I would need to do a lot more research on PyQt in order to get it to pop up the error window.

What are your thoughts?

**Comment by gedakc** [comment]
Thanks @RiderExMachina for looking into this issue.

Please add a link to the code in question so that I know which section of the code you wish to discuss.  It would help if you provide more description of what the "*offending flag*" is and the code changes you  propose.  Currently I am unable to read minds.  ;-)

Once I have a look at the code then we can examine what our options are going forward.

**Comment by gedakc** [comment]
Thank you @RiderExMachina for diagnosing this issue and explaining your rational and including links to where the problem was introduced.

From looking at the code, the file [`manuskript/functions/__init__.py` contains the statusMessage method](https://github.com/olivierkes/manuskript/blob/master/manuskript/functions/__init__.py#L356).  This method optionally accepts two paramters: `duration`, and `importance`.

My interpretation of the [`manuskript\mainWindow.py line 556 call of the F.statusMessage(...) method`]() is that it is intended to pop open a dialog with a message indicating the file does not exist.

It appears that the `importance=3` argument is intended for the `statusMessage()` method, and not the `tr()` method.

Can you try moving `importance=3` so that it applies to the `statusMessage()` method?

For example:

```
F.statusMessage(
    self.tr("The file {} does not exist. Try again.").format(project), importance=3)
```

Please document your test steps with how you demonstate the issue occuring.  That way it is easier for me to recreate the issue and then confirm if a proposed patch corrects the issue.

Thanks,
Curtis

**Comment by RiderExMachina** [comment]
@gedakc 

That works! It brings up red text in the bottom-right corner that says "The file <file> does not exist. Try again." I'll create a new branch and create a PR to resolve the issue. Thank you for the suggestion!

**Comment by gedakc** [comment]
Closing this issue as resolved in the **develop** branch.
