### ISSUE TITLE
[FEATURE IDEA] Can we get access to it with some APIs

### ISSUE THREAD

**Issue by palsumit** [olivierkes/manuskript#380]
I would like to run this as a server somewhere and write a web UI for this. This way I can take it on the go and work on my stories when I get some time anywhere.

**Comment by gedakc** [comment]
There are no plans to re-work Manuskript to be a server application.

If you wish to edit Manuskript scenes on a smart phone (or other device) then consider the following steps:

1. Use the [Open and plain-text file format](http://www.theologeek.ch/manuskript/2016/03/31/open-plain-text-file-format/) and ensure "**save to one single file**" is disabled.
2.  Copy / synchonize the Manuskript project files from your Manuskript computer to the smart phone (or other device).
3.  Edit the scenes on the smart phone (or other device).
4.  Copy / synchronize the Manuskript project files from the smart phone back to your Manuskript computer.
5.  Edit chapters / scenes / characters / etc. on your Manuskript computer.

Closing this issue as **invalid** so that it does not show up in the automatically generated CHANGELOG.md file.
