### ISSUE TITLE
Problems with running from 0.7.0 pyinstaller package on mac os x 10.13

### ISSUE THREAD

**Issue by lechbaczynski** [olivierkes/manuskript#386]
I’m not sure whether it is a manuscript bug, or rather pyinstaller problem, or python problem.

Sorry, I do not know python and its quirks well. Maybe @katafrakt will know

Anyway, while using Mac OS X everyone expects it to run smoothly, and install software smoothly.

Tried installing Manuskript on High Sierra 10.13 following instructions: “Download manuskript-0.7.0-osx.zip, unzip it (double-click). In the newly created manuskript folder find the file named manuskript and double-click on it.”

And I got errors like:
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>

I tried to find solution online, played around with PYTHONPATH
and 
PYTHONHOME

Also did brew install python3, and then got another errors:

Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00007fff8cc85380 (most recent call first):
Abort trap: 6

The python version is 3.7

Tried to fix it, but couldn’t. Gave up, checked out sources from git, installed dependencies and it works smoothly (both 0.7 and latest develop version).

Running the version from zip file still fails, though.

Maybe it is problem with installer, see those for info:

About pyinstaller not supporting 3.7:
https://github.com/pyinstaller/pyinstaller/issues/3219

About similar error in vim:
https://github.com/SpaceVim/SpaceVim/issues/1296
And their fix:
https://github.com/vim/vim/commit/0424958bde3d3e74c721ba39ab4d5a4744897393

**Comment by gedakc** [comment]
Thank you @lechbaczynski for reporting this issue and trying to locate a root cause.

# Investigation

## Similar error in vim?:

I looked at the SpaceVim/vim links you provided and these appear to indicate an issue with the `PYTHON3_PATH` being hard coded in vim.  I did a search for `PYTHON3_PATH` in the manuskript code base, but did not get any hits.  Hence it appears that the `PYTHON3_PATH` is not hard coded in manuskript.

## Pyinstaller not supporting Python 3.7?:

The PyInstaller build for Mac OS X was automated thanks to @katafrakt.  This occurs in the Travis Continuous Integration virtual environment.  The Mac OS X PyInstaller build log for manuskript 0.7.0 can be found at the following link:

[Travis CI - olivierkes/manuskript - build 133](https://travis-ci.org/olivierkes/manuskript/builds/416424560)

The deploy of the `manuskript-0.7.0-osx.zip` file to olivierkes/manuskript release area can be found near the bottom of the log (~line 6659).

The build of the Mac OS X PyInstaller package starts about line 51.  From looking through the log file, it appears that Python version 3.7.0 was used about line 3606.

This leads me to believe that the root cause is that PyInstaller did not support Python 3.7 at the time of the automated build (August 15, 2018).

# Possible Solution

It appears that PyInstaller 3.4 was released on Sept. 9, 2018 and that it includes support for Python 3.7.  See [Changelog for Pyinstaller](https://pyinstaller.readthedocs.io/en/stable/CHANGES.html).

We could prepare for another Manuskript release soon so that the new PyInstaller is used in the automated build.

Prior to this we should test to see if the *dev* builds for Mac OS X work.

A list of all the automated builds can be found at:

[Travis CI - olivierkes/manuskript - Build History](https://travis-ci.org/olivierkes/manuskript/builds)

On Sept 11, 2018 there was an [automated build 136](https://travis-ci.org/olivierkes/manuskript/builds/427289409) that created a `manuskript-osx-develop.zip` file.  This build appears to have used PyInstaller 3.4 (~ line 3908)

@lechbaczynski, would you be able to download the recent [`manuskript-osx-develop.zip`](www.theologeek.ch/manuskript/releases/manuskript-osx-develop.zip) file to test to see if it works?

Thanks,
Curtis

**Comment by lechbaczynski** [comment]
I downloaded from http://www.theologeek.ch/manuskript/releases/manuskript-osx-develop.zip

opened Downloads/manuskript/manuskript. and it works :) (runs the program, not installs it)

**Comment by gedakc** [comment]
Thanks @lechbaczynski for confirming that the *dev* version works.

Because I do not access to Mac OS X to manually rebuild the package using the 0.7.0 source code, I will look into using the current *dev* version to replace the original 0.7.0 version package.

The *dev* version only has [two additional commits](https://github.com/olivierkes/manuskript/commits/develop) beyond the 0.7.0 release.  One of these commits is yours to prevent a crash on export.  :-)

**Comment by gedakc** [comment]
For Max OS X I have uploaded the current *dev* PyInstaller package to replace the original 0.7.0 package (which didn't work).

The new package file is named [`manuskript-0.7.0-2-osx.zip`](https://github.com/olivierkes/manuskript/releases/download/0.7.0/manuskript-0.7.0-2-osx.zip).  It contains the following two extra commits over and above what was included in the original 0.7.0 release:

 - 3fdef2b8 - Fix for compile/export crash (error when saving in cp1250)
 - 2fdf8c64 - Minor grammar fixes

Thanks again @lechbaczynski for reporting this issue and then confirming that the *dev* package did work.

**Comment by gedakc** [comment]
Due to issue #390 which was introduced by pull request #383 which was included in the **develop** branch when `manuskript-0.7.0-2-osx.zip` was created, a new `manuskript-0.7.0-3-osx.zip` has been created.

The new package file [`manuskript-0.7.0-3-osx.zip`](https://github.com/olivierkes/manuskript/releases/download/0.7.0/manuskript-0.7.0-3-osx.zip) contains the following extra commits over and above what was included in the original 0.7.0 release:

- 3fdef2b - Fix for compile/export crash (error when saving in cp1250)
- 5f8168fb37 - Moved incorrectly placed parameter to correct place.
