### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by lczaplys** [olivierkes/manuskript#392]
I've spent about 3 hours trying to install your program. 

I like what I've seen and heard about it but it is just too difficult to install while other opensource programs aren't.

Can't you make it easy to install? I don't think you'll get the feedback you need to improve your program until you do.

**Comment by gedakc** [comment]
In order to help we need more information from you.

What OS are you using?
Which manuskript file did you download to install?

**Comment by lczaplys** [comment]
Hi,

 

I was able to install with this file: manuskript-0.6.0-win32 with no issues at all.

 

Thanks.

 

Larry

**Comment by gedakc** [comment]
There is a newer version 0.7.0 available for Download from either [Github](https://github.com/olivierkes/manuskript/releases) or [SourceForge](https://sourceforge.net/projects/manuskript/files/manuskript/).

This newer version uses the exact same installation method as version 0.6.0.

Does 0.7.0 work for you?

**Comment by gedakc** [comment]
In order to help we need more information.

What didn't work for you with 0.7.0?

For example, you could not unzip the file?  You were unable to run the manuskript.exe executable?

If you have problems running the program, open a command prompt, change to the directory with manusrkipt.exe, and then enter `manuskript.exe` to run.  Then copy any messages from the command prompt and paste them into this issue thread so that we can triage the problem further.

**Comment by lczaplys** [comment]
Sorry I cannot be of any more help. It works fine now.

 

In all cases where it didn’t, the command prompt that opens (and stays open when the program runs) showed two lines for a few seconds and then closed.

**Comment by gedakc** [comment]
Thank you for reporting that 0.7.0 works fine now.

If you experience an issue in the future, please try running manuskript from a command prompt and copy and paste the text into a new issue report.

Closing this issue as **invalid**.
