### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by bilelmoussaoui** [olivierkes/manuskript#425]
Here are few things that should be fixed before I can push a fully working Flatpak package to Flathub. 

- The desktop file:
https://github.com/olivierkes/manuskript/blob/master/package/create_deb/manuskript.desktop
The Exec shouldn't have the full path of the binary file. You should just use `manuskript`
The Icon shouldn't use the full path neither. You should use a RDNN name (Reverse domain name for the icon attribute). Something like `ch.theologeek.manuskript`, the desktop file must be renamed to `ch.theologeek.manuskcript.desktop` too.

- Missing AppData File
Currently, the app doesn't have an appdata file, it's used by Software centers to show up some info about the application like: Description, Screenshots, Releases info, a lot of others information that could be helpful for users.

**Comment by bilelmoussaoui** [comment]
Is there a reason for not using a build system like Meson/CMake/Autotools ? You seem to still use pyinstaller, which is good, but won't allow you to get the i18n and some stuff without doing some hacks around :)

**Comment by gedakc** [comment]
Is there a reason for not using a build system like Meson/CMake/Autotools ?

No specific reason.  I use autotools on another project, but don't know how this would work with this project.

As of Manuskript 0.6.0 we use `.deb` for Debian based distros and `.rpm` for Fedora based distros.  See [`package/create_deb.sh`](https://github.com/olivierkes/manuskript/blob/master/package/create_deb.sh) and [`package/create_rpm.sh`](https://github.com/olivierkes/manuskript/blob/master/package/create_rpm.sh) respectively.

We continue to use PyInstaller for Windows and Mac OS X.

**Comment by gedakc** [comment]
See also issue #71 which is a request for additional package formats.

**Comment by bilelmoussaoui** [comment]
The current scripts used to generate a deb/rpm packages are not a suitable build system to be used by a random contributor/user. I would suggest using meson build system for this project which will allow you to easily setup and improve the dev experience for this app.

**Comment by ramcq** [comment]
Hi @bilelmoussaoui, do you have a WIP flatpak for this app which you could share here? I'm worried the existence of this issue (with no progress) could discourage other people from working on it. If you're not actively working on it, if you share what you have then people might be able to pick up where you left off. IMO changing the build system or advocating for meson is a separate ticket and shouldn't be considered a blocker here to having a basic flatpak.

**Comment by TheJackiMonster** [comment]
I have started getting a flatpak working with the commit 0d687b6. There's still much to tweak because Pandoc isn't included yet, the .desktop-file needs to be installed correctly and such. Also somehow installing pyenchant doesn't seem to get registered in the Manuskript flatpak-application even though it works fine the same way for pyspellchecker and others.

There's also some problem with language-tool-python when I tried adding it as a module. But maybe this can be fixed to provide all features out-of-the-box with the flatpak. I want to get this working before the next release because the snap package is still not updated to 0.12.0 as well.

**Comment by TheJackiMonster** [comment]
I've tried my best to get at least `language-tool-python` working in the flatpak but it hasn't worked so far. I assume this can only be fixed by installing all dependencies for it properly. However `tdqm` failed building as well and I'm also not sure yet if the flatpak extension for openjdk worked properly in my trials.

So for now I will just ship the flatpak as it is now. So LanguageTool will not be supported and the PDF preview will not work. Otherwise everything should be fine which is a lot better than not getting the newest version running at all.

I hope it will help to get the flatpak on flathub. Maybe someone over there can help with packaging or at least somebody notices that the flatpak-pip-generator needs some additional work. Because if flatpaks want to replace usual packages it really shouldn't be 3x times harder to build it. ^^'
