### ISSUE TITLE
Lock cursor height

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#439]
It would be great, if one could lock the cursor to a certain screen height. As one starts a new row, the whole text shifts up, instead of the cursor moving down to the next row. That prevents the cursor spending most of its time at the bottom of the screen. Otherwise people working on a laptop tend to tilt their head forward, putting strain on their neck.

**Comment by scribas** [comment]
Hi

I actually did try that, because I thought that was what it was for. But
maybe I did something wrong. Will try again.

**Comment by gedakc** [comment]
After enabling **Typewriter mode** be sure to exit manuskript then start up manuskript again.  This is required to activate a number of the GUI change settings, such as when changing the **Language**.

![manuskript-general-settings](https://user-images.githubusercontent.com/10405019/49898953-95755e00-fe17-11e8-8f87-58e55ba136af.png)

There is a note to this effect on the **General** pane of the **Edit -> Settings** window as shown in the above screen shot.

**Comment by scribas** [comment]
Ah, did not see that. That will be the reason. Perfect!

I went and bought Scrivener a couple of years ago, but am looking for
something that will run on Linux too. Manuskript has dramatically improved
since I last checked it out. It has pretty much the same features as
Scrivener, but more intuitive and free! You are definitely on to a winner
here!

Have you considered buying up Story Weaver and merging it into Manuskript?
Then you would be ahead of the whole market and could consider changing to
a freemium model :-)

**Comment by scribas** [comment]
One more thing. I just stumbled upon the tutorial at:
http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing

Any chance you can include that as a Tutorial item in the help menu?

Kind regards
Dr Stefan Scriba
083 212 7724

**Comment by gedakc** [comment]
Did enabling **Typewriter mode** work for you?

If so then we can close this issue.

> Have you considered buying up Story Weaver and merging it into Manuskript?
> Then you would be ahead of the whole market and could consider changing to a freemium model :-)

Manuskript is a Free Libre Open Source Software project that exists due to the generosity of volunteers.  There are no plans or funds to purchase other software or to charge a fee.

> One more thing. I just stumbled upon the tutorial at: http://gedakc.users.sourceforge.net/display-doc.php?name=manuskript-novel-writing
> Any chance you can include that as a Tutorial item in the help menu? 

You might notice that I wrote that tutorial.  :-)

A link is included on the [Manuskript Wiki](https://github.com/olivierkes/manuskript/wiki) entitled "Using Manuskript to Write a Fiction Novel".

It is an introductory tutorial that is not written as a help manual and missing many manuskript features.  Help manuals are structured differently (for example see the [GParted Manual](https://gparted.org/display-doc.php?name=help-manual) that I wrote a number of years ago).  Writing a help manual for Manuskript is an available volunteer opportunity.

**Comment by scribas** [comment]
Sorry, yes, Typewriter mode worked perfectly! I also installed Manuskript
on my Linux environment at home this morning. I found a very nice article
on the 3 Act Story technique and now structured my Manuskript environment
accordingly, with the article copied and pasted into lots of little 'Aim'
text areas, to guide me as I write.

I read through the entire wiki and tutorial yesterday. (I have seriously
had enough of my actual work for one year, so spending a bit of time on
more creative stuff).

And I checked out some of your GParted work and books on Amazon yesterday.
You are one elusive online character, hahaha. But some serious
contributions to humanity. Respect!
