### ISSUE TITLE
Full-screen mode right-click menu black text on black background

### ISSUE THREAD

**Issue by scribas** [olivierkes/manuskript#440]
When I right-click in full-screen mode, the menu that pops up has a black background, with colourful icons. Only once I hover over any of the menu items, does the font change to white and I can actually read the menu item. The rest all have a black font, on a black background. I don't seem to be able to find a place in the settings, where one can change either the background nor foreground colours of this popup menu.

**Comment by gedakc** [comment]
Thank you @scribas for reporting this issue.  Also thank you @kakaroto for providing a fix.

I confirmed the problem on Windows XP and Kubuntu 16.04 with the black text on black menu background with the right-click menu in fullscreen mode for the **writingdesk** and **spacedreams** themes.

![manuskript-fullscreen-writingdesk-menu-unreadable](https://user-images.githubusercontent.com/10405019/53357846-004d1600-38ec-11e9-95ad-b2b84f1b3a98.jpg)

Note that the **Gentle Blues** and **oldschool** themes have right-click menus that are more readable.

![manuskript-fullscreen-oldschool-menu-readable](https://user-images.githubusercontent.com/10405019/53358129-b44ea100-38ec-11e9-9ce6-2746ee0b8465.png)

**Comment by gedakc** [comment]
Following is a a screen shot with the right-click menu in fullscreen mode for the **writingdesk** theme **after the fix was applied**.

![manuskript-fullscreen-writingdesk-right-click-menu](https://user-images.githubusercontent.com/10405019/53359926-73a55680-38f1-11e9-8bc2-4903096ab9dd.jpg)

This enhancement has been committed to the **develop** branch and will be included in the next release of Manuskript.

**Comment by scribas** [comment]
Wow, awesome fix!
