### ISSUE TITLE
Context/right click Menu slow and only in english

### ISSUE THREAD

**Issue by madeonearth** [olivierkes/manuskript#487]
**Context/right click Menu slow and only in english**

**1.** I noticed that when you initially try to open the right-click menu in tree view but within other txtBoxes too it takes up to 7 seconds to pop up. Now that does not sound long but actually is when you expect something to happen! At first I did not think anything would happen and clicked around a bit. While the menu was not visibl yet it was sensitive for my interaction and I started operations I did not want to. e.g. deleting a scene, creating a new folder. Also Manuskript got unresponsive for a little bit until it caught up.
After invoking the menu for the first time it loads very quickly from then on.
This might just take a little getting used to, but for a first time user it could look like an issue.
I just thought I'd mention this ...

**2.** Is there a way to translate those menus to other languages?
   The translation files seem not to refer to the context menu items!

**Comment by gedakc** [comment]
Regarding (1) what computer / processor / Operating System are you experiencing the slowness on?

Regarding (2) there are several translation fixes in the queue for the [0.9.0 milestone](https://github.com/olivierkes/manuskript/milestone/8) (see closed issues).  Further the status of translations can be viewed at [Weblate - Manuskript](https://hosted.weblate.org/projects/manuskript/translations/).

**Comment by kakaroto** [comment]
I had the slow right click issue as well, but it's not 7 seconds for me. I just tested and counted, it took 26 seconds to unfreeze after I right click on a folder in the editor view, then 36 seconds in a second attempt, and it took 33 seconds in the outline view, then 32 seconds in the second attempt. During the time to entire window is frozen. While it does work much faster (1 second) for subsequent right clicks, from my past experience, it only lasts a few minutes, then the right click will become slow again.

This issue completely disappeared after I switched to the development tree. I installed python 3.7 (32 bits version on Windows 10), then ran 'pip install pyqt5 lxml pyenchant' and created a shortcut to the python install so it runs manuskript from source, and now the right click freezing is gone.

My guess is that the way the executable is created is causing the slow down, either due to the self contained/compressed python, or for some other reason. I can also confirmed not having this issue on a Linux machine (Fedora)
Either way, assuming you are in the same situation, it looks to me like a packaging issue rather than a code issue.

**Comment by madeonearth** [comment]
**1.** Win10 64 AMD A6-1450 APU 4GB
**2.** ([Weblate - Manuskript](https://hosted.weblate.org/projects/manuskript/translations/).) ... very interesting. I did not know this existed, just had a quick glance. Should I use the 'suggest translation' function of that page to contribute?
Would you please point me to where I can find the context menu regarding entries. I tried to search for them but could not find anything related.

**Comment by gedakc** [comment]
2. Try reading through the 0.9.0 milestones.  I think you'll find that the issue is already addressed.
