### ISSUE TITLE
Odd wordchoices in English.

### ISSUE THREAD

**Issue by therahedwig** [olivierkes/manuskript#53]
I am not a native English Speaker(Dutch), but I can tell your native language(French) : p 

Infos - Information and Info don't have multiples in neither English nor French. So this should be **Info** or **Information**
Redaction - In English this would be **Editing**. While redaction seems to be an English word, I have never seen it in the "wild", they tend to use editing and editor in all cases.

I'll add more when I come across them :)

**Comment by fitojb** [comment]
Indeed, _[redaction](https://en.wiktionary.org/wiki/redaction)_ in English is an uncommon word and _also_ a [false friend](https://fr.wikipedia.org/wiki/Faux-ami), because it means something different.

**Comment by gedakc** [comment]
I am a native English speaker and I agree that _redaction_ is not a common or the correct word for this menu/button entry.  In the navigation pane, the _redaction_ section is used for _editing_ or _writing_.

In fact, _Write_ is the help text for redaction.  See [manuskript/mainWindow.py: Help Box - "Write" - line 844](https://github.com/olivierkes/manuskript/blob/master/manuskript/mainWindow.py#L844).

Because the navigation pane contains nouns, the word for this entry should also be a noun.

I recommend renaming **Redaction** to **Editor** in the navigation pane.

**Comment by olivierkes** [comment]
That's great, thanks. 

So for now we have:

  - Infos → Info or Information
  - Redaction → Editor or Editing

As @gedakc says, the navigation pane contains nouns. But then those nouns (Summary, Characters, Plots, World, ...) are attributes *of the book* (or whatever it is you write), not *of the software*. They refer to the book's summary, the book's characters, etc. In that line, would not the noun *Text* be more accurate? Or *Content*?

You tell me, I'll follow your decision :)

**Comment by gedakc** [comment]
Thanks @olivierkes for sharing your thoughts.

I spoke with my significant other who is using Manuskript to write her fourth novel.  Regarding the word **Redaction**, she suggests using a verb such as **Compose** to make it stand out as being the core area where you write the novel.

If you prefer to have a noun only, she suggests **Editor**.

She is not a fan of **content** or **text** for this section of Manuskript.  I agree with her on this.

Our vote is as follows:

- Redaction -> Compose (if a verb) or Editor (if a noun)

**Comment by StuartLeonard** [comment]
Just to add my input (as a native English speaker), when I first tried the application I skipped over the Redaction screen and was looking for an Edit screen. 

Edit or Editor would be my preference, with Compose my second choice.

**Comment by gedakc** [comment]
I think **Editor** is a good choice.

One other option I thought of is to replace **Redaction** with **Story**.  Thoughts?

**Comment by Exitr** [comment]
Redaction
noun

"1. Putting something (as a literary work or a legislative bill) into acceptable form.
synonyms: editing

2. The act of putting something in writing."

(Source: Power Thesaurus)

**Comment by gedakc** [comment]
One of the challenges with a word such as **Redaction** is that it has other definitions that I think are more commonly known, such as the first one listed below.

- [The Law Dictionary](http://thelawdictionary.org/redaction/)
  What is REDACTION?
  The process of redaction is when a document is modified, edited or revised to have all confidential and sensitive information taken out of it.

- [Miriam Webster Dictionary](https://www.merriam-webster.com/dictionary/redact)
  Definition of redact
  transitive verb
  1. to put in writing
  2. to select or adapt (as by obscuring or removing sensitive information) for publication or release; broadly
  3.  to obscure or remove (text) from a document prior to publication or release

- [Oxford Dictionaries](https://en.oxforddictionaries.com/definition/redaction)
  redaction
  noun
  1.  The process of editing text for publication.
  1.1 The censoring or obscuring of part of a text for legal or security purposes.
  1.2 A version of a text, such as a new edition or an abridged version.

- [Collins Dictionary](https://www.collinsdictionary.com/dictionary/english/redaction)
  redaction in American English  (rɪˈdækʃən ; ridakˈshən)
  noun
  1. the preparation of written work for publication; editing, reediting, or revision
  2. an edited work; esp., a reissue or new edition

- [The Free Dictionary](http://www.thefreedictionary.com/redaction)
  re·dac·tion  (rĭ-dăk′shən)
  n.
  1. The act or process of preparing a document for publication, especially by deleting private or sensitive information.
  2. An edited work; a new edition or revision.

Because we have not been able to come to a consensus on replacing the word **Redaction**, I think we should keep it for the time being.

Regarding the text **Infos**, I think we should change it to either the short abbreviated form **Info** or the long form **Information**.  The text **Infos** is not an English word.

**Comment by camstevenson** [comment]
For what it's worth (and I'm kind of sorry to reopen this): as a new user, this was one of a couple of things that was a genuine speed bump to start using the app.

"Cool," I thought, "there's some way to do redactions in documents.  How do I actually edit though?"

My suggestion would be to pick *something*, be it Story, Content or whatever that eliminates the "adoption speed bump" for English speakers.  It can always be refine/changed later.

(Also, happy to make any code changes)

**Comment by olivierkes** [comment]
Thanks for resurrecting this :)

So:

- Redaction → Editor
- Infos → Info (in most places where it's visible)

This issue is open for more suggestions.

**Comment by gedakc** [comment]
I am in agreement with the above word choices outlined by @olivierkes.

**Comment by gedakc** [comment]
Two more suggestions to improve the English wording.

* Serie -> Series

_Note that there is a trailing "**s**"_

* Informations -> Information

_Note that there is no trailing "**s**"_

**Comment by olivierkes** [comment]
Thanks. I've seen many "informations", i'll change them. But where did you see a "serie" that should become "series"? Is it in the general book information?

Also I seem to recall something about the term "Revisions". Is that right? If so, how should we call that?

**Comment by gedakc** [comment]
The word "Serie" is contained in the file [manuskript/ui/mainWindow.py](https://github.com/olivierkes/manuskript/blob/3b1a3f7fdef2df8a8270703420dff884a0edd985/manuskript/ui/mainWindow.py#L1231) and is displayed on the _Book Information_ pane along with "Title", "Subtitle", "Volume", etc.

I think the correct word for this location is "Series".

For example my spouse has written three novels in _[The Medusa Legacy](https://lindatemple.com/)_ "Series".  The first book or "Volume" one in the series is _[The Medusa Deception](https://lindatemple.com/the-medusa-deception/)_.

The word "Revision" implies a number or a date indicating a specific release of the novel, similar to a revision control system for source code.

**Comment by gedakc** [comment]
Because we already have updated translations being added to Manuskript for the 0.5.0 release, I think we should create a new issue for any word changes in this issue that have not yet been committed.  Then we can close this issue so that it does not hold up our efforts to roll out 0.5.0.

@olivierkes what do you think?

**Comment by olivierkes** [comment]
Good idea @gedakc, would you mind doing it?

**Comment by gedakc** [comment]
New issue #181 created.  Closing this issue.
