### ISSUE TITLE
[Feature Request] Save Dialogue/Indicator

### ISSUE THREAD

**Issue by MagpieWorks** [olivierkes/manuskript#551]
It would be nice if there were some sort of indication or status bar on the document to show that it has finished saving. I know that the editor view has the revision box off to the side, but that just seems to just autosave on occasion, and isn't related to saving the document as a whole. And there is no save indication at all in any of the other interfaces, like Characters or Plots. If something like this could be implemented it would be very appreciated.

**Comment by gedakc** [comment]
Manuskript does have a save notification that is temporarily shown in the lower left hand corner of the window.  Note that the message text is light gray so that the save notification is not overly distracting.

The following screen shot shows the save message while in the Character pane.

![Manuskript-Character-Save-Message](https://user-images.githubusercontent.com/10405019/58124714-13f6d880-7bcc-11e9-9bf2-f73a65a74f08.png)
  ^^^
Look here.

Does that answer your question?

**Comment by gedakc** [comment]
Closing issue and labeling as **invalid** because a save indicator is shown and no further response has been received.
