### ISSUE TITLE
suggestion: Use sudo for your Fedora install instructions, not su -c

### ISSUE THREAD

**Issue by taw00** [olivierkes/manuskript#573]
In your installation instructions for v0.9, I noticed this...
"""
FEDORA Based (Fedora, CentOS, etc.)
Download manuskript-0.9.0-1.noarch.rpm, then install program and dependencies with:
  su -c "dnf install manuskript-0.9.0-1.noarch.rpm"
"""

I would suggest you just make that...
"""
sudo dnf install manuskript-0.9.0-1.noarch.rpm
"""
...just like the other instructions. It's how most folks would do it.

By the way. I just started playing with your application. I am a writer (and linux dork from forever). :)

**Comment by notsag** [comment]
Hey, I setup a copr repo for Fedora : https://copr.fedorainfracloud.org/coprs/notsag/manuskript/

You can now use : 
"""
sudo dnf copr enable notsag/manuskript
sudo dnf install manuskript
"""

For now there is only 0.9 packaged but the next one will be too.

**Comment by gedakc** [comment]
Has the default way of gaining root access in Fedora changed?

[Fedora Wiki: Differences to Ubuntu - The root account](https://fedoraproject.org/wiki/Differences_to_Ubuntu#The_root_account)

**Comment by taw00** [comment]
When you install Fedora, it asks if you want to give the initial user you set up system level privileges (ie. make it a sudo-enabled account). I don't know that any distro does this differently. I.e., You have that decision to make at install time (though, of course, you can make it later as well). Maybe Ubuntu checks that box ON by default and Fedora OFF by default. I dunno. I have never not flipped that bit and the installer, IIRC, suggests you do (it's been awhile since I installed Fedora fresh). But on the whole, every distro works the same in this regard.

**Comment by gedakc** [comment]
Thank you @taw00 for raising this issue.  It does indeed appear that RedHat has changed the default method of accessing root privilege.

Root privilege testing on fresh VM install of Fedora 30:

    [fedora@localhost ~]$ su -c "ls"
    Password: 
    su: Authentication failure
    fedora@localhost ~]$ sudo ls
    [sudo] password for fedora: 
    Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
    [fedora@localhost ~]$ 

This behaviour also occurs for Fedora 29 and Fedora 28, but not with Fedora 27.

Testing on Fedora 27 VM:

    [fedora@localhost ~]$ su -c "ls"
    Password: 
    Desktop  Documents  Downloads  Music  Pictures  Public  Templates  Videos
    [fedora@localhost ~]$ sudo ls
    [sudo] password for fedora: 
    fedora is not in the sudoers file.  This incident will be reported.
    [fedora@localhost ~]$ 

Hence it would appear that starting with Fedora 28 RedHat has changed the default method of accessing root privilege from "su" to "sudo".

Because [Fedora 27 and lower are no longer supported](https://en.wikipedia.org/wiki/Fedora_%28operating_system%29#Releases), I have changed the Manuskript 0.9.0 install instructions for Fedora on the Manuskript Download page.
