### ISSUE TITLE
[Bug] Next Button in Characters Pane

### ISSUE THREAD

**Issue by ghost** [olivierkes/manuskript#584]
Small thing here, but thought I should mention it.

There is a Next button in the both the Summary Pane and the Characters Pane (and only in these two panes). Clicking on Next in the Summary Pane takes you to the next pane, Characters. However, clicking on Next in the Characters Pane, rather than taking you to the next Pane, Plots, instead takes you back to the Summary Pane.

If I may, I would suggest the behavior of the Next button in the Characters Pane be changed to take the user to the Plots Pane. Or, if this is the intended behavior, that the Next button in the Characters Pane be changed to a Back button, to be more obvious of its direction. 

Best.

**Comment by gedakc** [comment]
My guess is that the original author of Manuskript intended the **Next** button to be a **Novel Assistant** that would guide a person through the initial steps of creating a novel using the [Snowflake Method](https://www.advancedfictionwriting.com/articles/snowflake-method/).  I think this because the the **Novel Assistant** is mentioned on the front page of the [Manuskript](https://www.theologeek.ch/manuskript/) web site (scroll down to **Features** section).

If my guess is correct then the current behaviour is incomplete.  It should likely end up at the **Editor** pane after going through some of the other panes.

**Comment by mikeandjam** [comment]
@gedakc Aha! So you believe the original intent was that there would be a **Next** button in each pane, excluding the General and Editor panes?

For my own part, I think such buttons would be unnecessary. A user can already access every pane (in the intended order) through the left navigation bar. The only reason they would not be able to do so would be if they had Manuskript in Simple Mode rather than Fiction, in which case they would probably not be using the Snowflake Method anyway. I may just be that much of a clod, but I did not even realize there *was* a **Next** button in the Summary and Characters panes until I went over each piece by piece for writing the [Overview of Manuskript Panes](https://github.com/olivierkes/manuskript/wiki/Overview-of-Manuskript-Panes).

If I am not overstepping, I personally think the best solution would be to just cut the Gordian Knot and remove the **Next** button from the Summary and Characters panes. It seems as though the buttons are vestiges of a feature that never got fully implemented, and would not have served any greater purpose even if it were. And of course, there is the issue that they presently do not seem to work properly in the first place.

Best.

**Comment by gedakc** [comment]
> So you believe the original intent was that there would be a Next button in each pane, excluding the General and Editor panes?

Yes.  Only the original author can confirm if this is indeed the case.

I agree that the **Next** buttons as implemented are not overly useful.  Personally I think they should be removed as well.  If you are up to digging into the source code then a pull request implementing your suggestion would be the next step.

**Comment by mikeandjam** [comment]
@gedakc Well unfortunately now I have to admit my dirty secret; the extent of my familiarity with code is HTML and CSS. While I would like to contribute to the project in a more substantial way, I would have no idea what to look for if I were to try digging into the source code, nor do I know how to implement a pull request.

I am afraid the most I can contribute is in writing up documentation, and I do plan to flesh out and expand what I have written so far going forward. Making changes to the code however I suspect is rather beyond me.

Best.
