### ISSUE TITLE
Issue with saving as directory

### ISSUE THREAD

**Issue by eternalsage** [olivierkes/manuskript#589]
Working on Windows 10, have laid out my outline and copied in the relevant information from my previous google docs version, then realized I had forgotten to change to directory mode ("save to single file" was still clicked on). When I clicked this off and hit save it crashed.

It has now crashed numerous times. I'm not sure if it is a bug, an installation issue, or even just a file problem. BTW I thought it might be because of the length of file/folder names and the depth of files, but I moved the files to the base of a different drive and it seems to die in the same place. The output from commandline is below.

```
C:\Users\Jason\manuskript-0.9.0-win32>manuskript.exe
Debug: Web rendering engine used: QWebView
Running manuskript version 0.9.0.
Note: No translator found or loaded from system locale for locale en_US.
Loading: E:/Drive/Manuskript/VERS_BaseRules.msk
Detected file format version: 1. Zip: True.
Project E:/Drive/Manuskript/VERS_BaseRules.msk loaded.
Traceback (most recent call last):
  File "manuskript\mainWindow.py", line 765, in saveDatas
  File "manuskript\loadSave.py", line 21, in saveProject
  File "manuskript\load_save\version_1.py", line 382, in saveProject
FileNotFoundError: [Errno 2] No such file or directory: 'E:/Drive/Manuskript\\VERS_BaseRules\\outline\\1-Book_I_-_Player_Rules\\1-Chapter_II_-_Character_Rules\\7-Abilities_and_Equipment_-_Overview\\1-Abilities_-Optional-\\5-Understanding_Manifestations_Properties_and_Effects\\0-Understanding_Manifestations-_Properties-_and_Effects.md'

C:\Users\Jason\manuskript-0.9.0-win32>
```

**Comment by worstje** [comment]
It is indeed the length of the filename nesting that is breaking you up. If you count how long that path is, you'll see it is **270** characters long. The MAX_PATH constant (which is an ancient constraint that Windows still abides by unless applications specifically mark themselves compatible) ends at **260**... which means that your path runs into a problem.

I ran into the same problem myself a couple of months ago; you can check issue #517 for more information. There is a workaround listed in it that may work well enough for you, but that solution could potentially negatively affect the workings of other applications on your machine. (It probably won't, but changing MAX_PATH on your system is like changing the constant that defines gravity on earth; most programs are simply not prepared to deal the subtleties that follow from it.)

We may have to look into a more program-centric way to work around this issue on Windows at some point, because the workarounds we know of are not ideal.

**Comment by eternalsage** [comment]
Thank you, I will look into these options. I had a feeling it was something like this, however. Thank you!
