### ISSUE TITLE
Format buttons in text editor window not working

### ISSUE THREAD

**Issue by AngelArnal** [olivierkes/manuskript#59]
Linux Mint 17.3, manuskript-0.3.0-linux-1

Text format buttons (bold, italic, etc) at the bottom of the edit window don't work. No error message, just nothing happens.

**Comment by docaltmed** [comment]
Also in Ubuntu 16.10/Gnome Shell

**Comment by olivierkes** [comment]
Yep right, i haven't reimplemented yet after i switched from rich text format to markdown.
Need to do.

**Comment by Weej1** [comment]
closed my dupe ticket thing and adding that the keyboard shortcuts Ctrl+B , Ctrl+I, Ctrl+U do not work either. Thanks gedakc for pointing me here!

**Comment by darrelwright** [comment]
Are the formatting options still on the "to-do" list? I see they are still not working in the latest 0.5 development version.

**Comment by olivierkes** [comment]
Yes, I should do it for the next relases because it's confusing.

Those are the inline formats that could be added:

- **Emphasis:** `*emphasis*` produces *emphasis*
- **Strong emphasis:** `**strong emphasis**` produces **strong emphasis**
- **Strikeout:** `~~strikeout~~` produces ~~strikeout~~
- **Superscripts and subscripts:** `this is ^super^ but this is ~sub~` (github's markdown doesn't support that)
- **Code:** `` `code` `` produces `code`
- **Clean format:** to remove any formatting

Underline is not supported in markdown.

**Comment by gedakc** [comment]
Another thought is to remove the format buttons from Manuskript because adding format using markdown is relatively simple.

**Comment by olivierkes** [comment]
I removed buttons, but added a menu (for those who don't know markdown, and to enable keyboard shortcut):

![image](https://user-images.githubusercontent.com/1192933/33431446-a60045c6-d5d4-11e7-8a2e-cbb3b3c05e72.png)
