### ISSUE TITLE
version in Pop! OS app center (elementary app center) is only 0.8.0

### ISSUE THREAD

**Issue by mbuscemi** [olivierkes/manuskript#594]
The version of Manuskript on Pop! OS's app center (which is based on Elementary app center) is only 0.8.0. Please update to 0.9.0.

**Comment by gedakc** [comment]
Each GNU/Linux distro is responsible for managing the packages that they choose to include.  We do not have any control over these packages.  We only manage the packages that we make available on our [WordPress](https://www.theologeek.ch/manuskript/download/), [GitHub](https://github.com/olivierkes/manuskript/releases) and [SourceForge](https://sourceforge.net/projects/manuskript/files/) web sites.

You can either choose to install one of our packages / source code, or else contact your GNU/Linux distro maintainers to request them to update the package.

Closing this issue as **Invalid** because we do not maintain the GNU/Linux distribution packages.
