### ISSUE TITLE
File Randomly won't open

### ISSUE THREAD

**Issue by wolfwatcher33** [olivierkes/manuskript#597]
I don't know what the issue is but for some reason one of my files won't open. Here's a screenshot of the text that showed up for a second. Please help and be aware that I am very uneducated in this area, I just don't want to loss my days of work
![File Issues](https://user-images.githubusercontent.com/52430489/60470758-aeb4ef00-9c2f-11e9-9236-a460e331ca50.png)

**Comment by gedakc** [comment]
I think that this is an issue with invalid characters in the revision history XML file.  I believe it was fixed in the **develop** branch with Pull Request #578.  Note that his fix is not in version 0.9.0.

A similar problem occurred in Issue #529 that was fixed by @worstje.  You might consider fixing the project file(s) yourself, or else asking @worstje to help you.

**Comment by wolfwatcher33** [comment]
Thank you so much! I had issue changing the file name at first but after a little research I found outhow to do it

**Comment by worstje** [comment]
Change the filename? Judging from the error, I am unsure what you did to solve it by changing a filename. But I am glad it worked out for you. 👍 

Additionally, it would have been nice to see your original messed up file so that we can verify that whatever code caused this error has indeed been fixed so it won't happen again. It would be nice to verify the fix in the develop branch is indeed sufficient. 😄

**Comment by wolfwatcher33** [comment]
In order to change what was in the file I had to change the file name to a .zip I just copy pasted everything into a new file but the revisions.
Here is the original file
[Kin Story-.zip](https://github.com/olivierkes/manuskript/files/3355268/Kin.Story-.zip)
