### ISSUE TITLE
The plot line colours keep changing?

### ISSUE THREAD

**Issue by andreashsagen** [olivierkes/manuskript#6]
Hi again,

really love this software. It certainly has a lot of promise, so thank you for your work.

In redaction mode, when I enter text, the colours in the story line pane change with each keystroke. Is that a bug, or am I missing something?

**Comment by olivierkes** [comment]
Hi @andreashsagen,

Glad you like it !

Yeah that's a work in progress... Since plots don't have colors (as characters do), i assign a random color each time the line is drawn, which is both lazy and stupid :)

It will be fixed in the next release, i guess (i'll leave that ticket open as a reminder), but I'm working on more fundamental issues right now.

**Comment by olivierkes** [comment]
Fixed in develop.
