### ISSUE TITLE
Manuskript runs amok, with Project (Project is added)

### ISSUE THREAD

**Issue by obw** [olivierkes/manuskript#729]
I have started #726 and copied what we have from the Wiki and so on.

But after I added the source installation descriptions, Manuskript eat up all my RAM (16GB of real and 32GB of swap under Linux)!
Zipped Projectfile: [manuskript_doc.zip](https://github.com/olivierkes/manuskript/files/4128830/manuskript_doc.zip)

It's the latest development Version, updated Sunday 26.01.2020 (DD.MM.YYYY).

Additional Info:
 - Python 3.6.9
 - PyQt 5.13.1
 - Qt 5.13.0

The Problem is the text of the Windows Source installation. Well it looks like, when I make this part/scene empty Manuskript just works fine.

**Comment by worstje** [comment]
I was able to reproduce this on Windows. Let me see what I can figure out.

**Comment by worstje** [comment]
I have identified the cause of the bug that causes the hang. Submitting a patch isn't too difficult; my problem is mostly in not being sure what actually causes the bug to begin with.

The bug is caused by `cursor.moveCursor(cursor.Down)` returning false, a condition that we never check succeeds in this function. Clearly, it works fine most of the time... but not here! The specific call that causes the error is the one at the bottom of the `while self.cursorRect(cursor).top() != r2.top():` loop.

Even more interesting is the fact that, if you have the text opened up from last time when you start Manuskript, the call succeeds... but if you switch to a different text and go back, processing exactly the same document will suddenly cause it to hang. What is it that causes it to act differently?!

For the time being, adjusting the inner-most while loop in question like this seems to fix the behaviour for as far my limited tests have been able to ascertain:

    while self.cursorRect(cursor).top() != r2.top():
        r3 = self.cursorRect(cursor)
        r3.setLeft(self.viewport().geometry().left())
        r3.setRight(self.viewport().geometry().right())
        refs.append(ClickThing(r3, rx, rx.capturedTexts()))
        if not cursor.movePosition(cursor.Down):
            print("Failed to move cursor down. Break break break!")
            break

Regardless of whether someone can identify the reason for the behaviour, I do feel like adding comments and including debugging notices for weird failures like these would be useful to have in order to better understand the workings of this and other code as we move forward. (But I am a bit worried about adding them in the current build since we have enough print() spam as it is.)

**Comment by obw** [comment]
@worstje: I have just added your Quickfix, it's working thanks!

**Comment by DarkRedman** [comment]
I'm confused, what is Amok and how is it related to the Display images bug ?! I was thinking it could be Qt not handling bounding box for text overlay ?!
