### ISSUE TITLE
Italian spellchecker

### ISSUE THREAD

**Issue by Eusorph** [olivierkes/manuskript#730]
Hello,

I installed the  .dic. and .aff files, but when I run the spellchecker, Manuskript underlines everything.

**Comment by Eusorph** [comment]
Okay, I solved it, but people should know. The .dic and .aiff files for the Italian dic were full of crap at the beginning. I confronted them with the french and english and deleted all of the stuff at the beginning. Now it works, but Manuskript still runs super slow when the spellchecker is on. Fairly unusable this way.

**Comment by worstje** [comment]
I am not familiar with the spellchecker, but there's a lot of information missing to the point where identifying the issue is next to impossible.

**Which version / build of Manuskript on which platform?**

**If it is a manual build, which spellchecker are you using?**

**Where does one find the .dic and .aff files you are referring to?**

The slowness could be due to the spellcheck engine being used. The wrong underlining could be a fault in the dictionaries (which wouldn't be a manuskript problem), but it could also be because the library Manuskript relies on does not use the files as they are intended to.

**Comment by TheJackiMonster** [comment]
![Peek 2020-03-29 16-25](https://user-images.githubusercontent.com/13867397/77851525-fde97980-71d9-11ea-9144-6d96609cb3c8.gif)
The PR (https://github.com/olivierkes/manuskript/pull/747), I am working on, should bring at least an alternate for the spellchecker. Maybe this will help..
