### ISSUE TITLE
Right click → Insert Reference buggy when search term is followed by punctuation

### ISSUE THREAD

**Issue by Evrey** [olivierkes/manuskript#781]
If I have some text like `and Steve, always polite` and right-click `Steve` to turn it into a reference like `{C:2:Steve}`, the right click itself highlights the entire name. So far so desirable. However, as soon as I click »Insert reference«, Manuskript jumps forwards and selects the comma instead. There is no work around other than inserting a space between `Steve` and the comma. Same with colon, period, anything not whitespace.

**Comment by TheJackiMonster** [comment]
Okay, I think I could fix the second part with commit 0cb65c452e6c52c697b9437ef714257224e25db5. But potentially the first part will only work now if you select/highlight `Steve` first and make the right-click afterwards.

If you say you need automatic selection of names for replacement with matching references, please open another issue because this would be a feature request rather than a bug.
