### ISSUE TITLE
Default background for fullscreen mode is unusable [minor]

### ISSUE THREAD

**Issue by szopeno** [olivierkes/manuskript#79]
The default options for fullscreen edition (black menus with white text, dark background with black fonts) are absolutely awful and render the text inivisble. I suggest sticking with reasonable black-on-white, while possibly adding visual indication that this could be changed via setting option (or, better yet, just adding button/menu to change the theme inside the fullscreen mode)

**Comment by olivierkes** [comment]
Can you post a screenshot?
Because these are the defaults themes, and to me they are not that ugly: http://www.theologeek.ch/manuskript/2016/02/05/customizable-distraction-free-mode/

(And BTW you can customize everything in the theme and settings, and change the theme from inside fullscreen mode, by placing your mouse at the bottom of the screen)
