### ISSUE TITLE
Can only add characters to the "Minor" category

### ISSUE THREAD

**Issue by gnu-lorien** [olivierkes/manuskript#826]
Can only add Minor characters. When clicking the + button in the names pane of the Characters pane it always adds the new character as a minor character.

Based on my experience with the World view it seems that new characters should be added to whichever category I've selected.

OS: Windows
Version: 0.11.0

**Comment by siliconserf** [comment]
Yes, you would expect the insertion to be in the category where the focus was placed, either by clicking on category or character. I verified the behavior just now. The code needs to be changed to notice current focus and set the category for the new character. It isn't so much a bug as a lack of sophistication. I'll take a look at it.

**Comment by siliconserf** [comment]
The code does track where the focus was when you add a new character, but fails to look there to see if it should create the character with that importance instead of the default "minor".  

While tracing through this I noticed there is an interesting bug in the Character editor. If you delete a character from the tree, _the character still displays_, but with all fields grayed out. This seems to be because until you save the project the character still exists as a file in the character directory. When the display is refreshed the character tree display code looks at the _character directory_ and finds the still existent character file. But the code knows the character isn't in the list in memory anymore so it paints the fields grey. You cannot edit the character. The text/folder tree code doesn't make that mistake, an argument for treating characters as text files/folders instead of a different class of object and dump the entire character support approach. Scrivener does this and it works nicely. I think this is a case where Manuskript is too clever for its own good and the bug doesn't warrant fixing.
