### ISSUE TITLE
Issue installing v12 on Win7 64bit

### ISSUE THREAD

**Issue by Goateechin** [olivierkes/manuskript#872]
Looking forward to giving version 12 a spin!
However, after unzipping and trying to run manuskript.exe I get an error. 
It's the same system I've been using v11 on without any problems - Windows 7 64bit

This is the error message:
manuskript.exe - Entry Point Not Found
The procedure entry point GetDaylightFlag could not be located in the dynamic link library kernel32.dll

I tried both the fixed and original version, just in case ;)
Also checked the dll was present and scanned my system files - all is up to date. Same error

**Comment by TheJackiMonster** [comment]
Hmmm, maybe that's because I build the file for 32bit. Currently I would recommend to use the older version (0.11.0) or try running Manuskript from source. But I will try to get another script done to build a 64bit version and maybe it will work in the future. I can't really test myself and I thought it would be fine since the person which tested it for me was on Windows 10 and I assumed the newer version would be less compatible. ^^'

**Comment by Goateechin** [comment]
Just to update - running 0.12.0 from source works fine

**Comment by demortes** [comment]
Would continuing to support Windows 7 be wise? It's been end of life for some time now.

**Comment by Goateechin** [comment]
> Would continuing to support Windows 7 be wise? It's been end of life for some time now.

Fair point. I just figured it was an issue that might appear elsewhere too so it was worth flagging.
It's a shame Windows 7 is dead, still the pinnacle of Windows imho.
I'm in the -very- slow transition to Linux and cross-compatibility is one of the reasons I started using manuskript in the first place

**Comment by worstje** [comment]
> Would continuing to support Windows 7 be wise? It's been end of life for some time now.

_Until recently_, Manuskript used to have a very rigid philosophy of not breaking any support with older versions. But given the hell that was giving us, that wasn't very feasible any longer. Qt alone was a nightmare of nightmares because supporting XP meant supporting an old version of Qt and everything inbetween, but that meant we kept hitting 'new' bugs in Qt and working around old bugs manually. In addition, I still have no clue exactly what sort of system and/or libraries gedakc used to build Manuskript with as his binaries were considerably different from what I could produce myself!

As such, I believe we have have sensibly limited ourselves to only supporting operating systems and versions thereof that are still in some form of official support.

This is all to lighten the support burden on the very small number of developers (and their time!) that we have to begin with, and enable the project to move on and attract fresh blood who want to help improve manuskript.

**Comment by TheJackiMonster** [comment]
> I still have no clue exactly what sort of system and/or libraries gedakc used to build Manuskript with as his binaries were considerably different from what I could produce myself!

I think it is mentioned in the wiki that he used a Windows XP system on bare metal to build it which was quite impossible for me to reproduce. However even though I kind of broke the support for Windows 7 with the build I could produce, maybe this looks a lot different when we can get rid of Qt. In my current script to build the Windows binary on Linux, there is even a part deleting libraries from the build-directory before creating the archive because they can break the runtime just by existence (I don't even know how Qt does that ^^').

For example it puts some Bluetooth libraries in the build-directory which throw some exceptions on startup of Manuskript. But as you can probably imagine, we obviously don't need Bluetooth in Manuskript. So my script deletes it and this makes the build run through Wine on Linux as well as on Windows 10. ^^'

Another hope for this mess is that Windows 10 and 11 offer WSL2 to run Linux applications on Windows (even displaying GUI). So maybe this could ease the build process as well in the future, if we can get a basic installer together which provides the Linux version on Windows.

**Comment by worstje** [comment]
Yeah, but that's exactly my point. I went through a lot of versions of PyInstaller while trying to build on a WXP VM of my own, and the closest I came was with a git revision that was right in the middle of their development cycle, and even that was considerably off.

I have a branch where I was trying to clean up the PyInstaller build as well, but I gave up on it because it seemed you were creating a completely different folder structure for your builds than I was. It's one bug bundle of madness, I tell you. 😁
