### ISSUE TITLE
Text pasted in Summary or Notes/References disappears

### ISSUE THREAD

**Issue by Biep** [olivierkes/manuskript#873]
Version 1.10.0
OS: Ubuntu 20.10

In the Summary and Notes/References fields of the Metadata pane, I can ***type*** information without problems.  However, if I ***paste*** text in it (even if copied from the same kind of field) it shows for just under a second, and then disappears spontaneously.  This is a bother with larger bits of text, which are not easily retyped by hand.
I like to copy background information from the Internet in the Notes/References fields, so that I can check those when I write the relevant scenes.
(And if you start working on that field - I wouldn't mind if it were hierarchical, the way the main writing area is.  You could reuse the same code, and I could then link some of the text files to all the scenes where the info is relevant - and to the appropriate places in Characters and World.)

**Comment by TheJackiMonster** [comment]
That issue is known... I think you mean version 0.10.0 which gets installed through apt. This was fixed in 0.11.0 already. You can either install the snap package (it should currently still be 0.11.0 until it gets updated) or you can install the .deb package with the newest version (0.12.0) manually from the [website](https://www.theologeek.ch/manuskript/download/).

**Comment by Biep** [comment]
OK.  I hope that 12.0 will make it into the Ubuntu 21.04 release - which still is not on official offer, due to some issue.
And thanks for all the good work!  Be blessed!
