### ISSUE TITLE
hide or get ride of the cmd window 

### ISSUE THREAD

**Issue by Reaper10** [olivierkes/manuskript#876]
Can you hide or get ride of the cmd window for good?
![Screenshot 2021-05-12 164007](https://user-images.githubusercontent.com/8137561/118048168-832de000-b341-11eb-8e7d-6fd6808939d3.jpg)

**Comment by TheJackiMonster** [comment]
I think this is a duplicate request of #327. So we are already aware of the problem which is Windows specific and it's still an issue that we will probably need to build two versions (one opening only our GUI and the other one allowing command line arguments).

I would close this here though because the discussion on the older issue is much bigger already.
