### ISSUE TITLE
(Windows, 0.12.0) "GetDaylightFlag" not found in "kernel32.dll"

### ISSUE THREAD

**Issue by mxamber** [olivierkes/manuskript#889]
Title says it all. I just downloaded the current release for Windows (last used 0.10) to bring it up to date with my Ubuntu machine (which already runs 0.12.0) but it won't start. Upon launching manuskript.exe, I get a pop-up with the following message: `Entry point "GetDaylightFlag" not found in DLL "kernel32.dll"`. Once I click OK, Windows informs that manuskript has crashed and the console window closes without anything written in it. I'm running an up-to-date 64-bit Windows 7.

**Comment by TheJackiMonster** [comment]
I think this is the problem we already had ealier with the 0.12.0 version on Windows 7. I already explained to a degree over here (#872) what's the issue.

Short version: I recommend to either update your operating system or to run Manuskript from source which is descriped [here](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) in the wiki.

**Comment by mxamber** [comment]
How big is the difference between 11 and 12? Meaning, will I run into any issues with features from my project not carrying over from 0.12 back to 0.11 and vice versa?

**Comment by TheJackiMonster** [comment]
The most features and changes in 0.12.0 are related to usability (more details here: https://www.theologeek.ch/manuskript/2021/04/30/manuskript-0-12-0/). So you can still use 0.11.0 if running from source should be too much hassle and upgrading the operating system is not wanted either.

Projects opened with 0.12.0 should still work fine with 0.11.0 because we didn't adjust the data model at all besides some optimization in providing each object in the plot a unique id. So you should be fine trying out to run 0.12.0 and hopping back if it doesn't seem to provide necessary features.

However because Manuskript is far from being reliable during all releases, I recommend copying your projects (or any other sort of backup) before any version change to be sure.

**Comment by mxamber** [comment]
Will try that! Too broke for a new Windows and not familiar enough with Python to run source, I'll make a backup and see if it works between versions (my Ubuntu laptop runs 0.12 just fine and I keep files sync'ed between the two).
