### ISSUE TITLE
Possible security issue

### ISSUE THREAD

**Issue by pizza-power** [olivierkes/manuskript#891]
Hi, do you have a process for reporting a possible security issue with Manuskript?

**Comment by TheJackiMonster** [comment]
I assume you can just post it here. There's no special process as far as I know. What kind of issue do you mean specifically?

**Comment by pizza-power** [comment]
Arbitrary code execution due to insecure deserialization in settings.py. 

Basically, I created a Version 0 project zip file containing a sample project with a malicious settings.pickle. loadsave.py sees it as v0 and sends it to v0.loadProject. 

Line 172 of version_0.py is where the following code calls the load function in settings.py

`settings.load(files["settings.pickle"], fromString=True)`

where on line 200 in settings.py pickle.loads insecurely deserializes your malicious settings.pickle file: 

`allSettings = pickle.loads(string)`

So I could post my sample project online for others to use, or send someone my project, and when they open it, arbitrary code will execute. 

Here are a couple of links to insecure deserialization in python, for those that aren't familiar with it

https://davidhamann.de/2020/04/05/exploiting-python-pickle/
https://frichetten.com/blog/escalating-deserialization-attacks-python/

**Comment by TheJackiMonster** [comment]
Okay, so I'm currently working on a huge refactoring which won't use pickle at all to load projects. So I assume this should be fine in the future. I'm also not sure if this is affecting only the older version 0 of load-/save-processes because the usage of pickle seems to be in settings.py.

For the moment I don't think this is affecting many people because most authors probably won't share their whole raw plots. Especially considering that Manuskript is still quite unreliable when it comes to not crashing and such. ^^'

I personally didn't even know there was such a module as pickle. So if you have a fix for this problem which can be applied soon, I can review the change. Otherwise I would add a disclaimer on the website to make users aware of the threat, so they don't open untrusted projects.

**Comment by pizza-power** [comment]
I was just looking at how to get to pickle.loads, and the first way I saw was from having a version 0 project. It seemed to be the only way, but I'd have to review the code some more to guarantee that.

The pickle module is inherently unsafe, and while there are some alternatives/workarounds for pickling and unpickling, if you're refactoring everything to a safer format, there probably isn't a reason to push a fix. 

I'd say a warning to not open unknown projects is probably sufficient enough.

**Comment by zeth** [comment]
The security fix would be to delete the code, it shouldn't be used any more. The current save format uses json stored in a text file that is much more secure.

**Comment by zeth** [comment]
This is just a sketch since I have no old data files to test with, we just ignore version 0 settings file.
https://github.com/olivierkes/manuskript/pull/895

**Comment by TheJackiMonster** [comment]
@pizza-power Do you think the fix will do it? Then I would close this issue.

**Comment by pizza-power** [comment]
> @pizza-power Do you think the fix will do it? Then I would close this issue.

Looks good to me. Thanks!
