### ISSUE TITLE
[Issue] Crash on Adding Second "Detailed Info" Entry for Characters

### ISSUE THREAD

**Issue by Zetawilk** [olivierkes/manuskript#908]
I downloaded and installed Manuskript for the first time ever this morning. (2021-07-27)

When I attempted to add a second entry for the only Character under its "Detailed Info" tab, the program immediately crashed to desktop. 

I did not see any issues specifically labeled with this cause and effect, and I have included a log. 

[2021-07-27_17-21-18_manuskript#16152.log](https://github.com/olivierkes/manuskript/files/6888835/2021-07-27_17-21-18_manuskript.16152.log)

**Comment by TheJackiMonster** [comment]
This has been fixed with the PR https://github.com/olivierkes/manuskript/pull/901. So to solve this for you without waiting for the next release, I recommend to run Manuskript from source ([here](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows) is a wiki entry explaining it in details).

Otherwise maybe try to avoid the character details in version 0.12.0 for the moment, make backups of your projects and wait for the next release. Hope this helps. ^^'

I will close this issue though because a fix is already merged to the main branch.

**Comment by TheJackiMonster** [comment]
The original issue was #843.
