### ISSUE TITLE
Entry Point Error, how can I solve this ?

### ISSUE THREAD

**Issue by LiegeVon** [olivierkes/manuskript#911]
![image](https://user-images.githubusercontent.com/88156010/127529104-1717814e-e20d-4967-8e6f-ecce72c545ab.png)

So uh, I wanna try get my hands on Manuskript since it has all the features that compliment my needs in writing. So of course I downloaded it, both version, one without the hotfix, and the other with that. And whenever I try to open the application, it just shows that error everytime. I'm no tech geek or anything, so I dont have any knowledge on why this happen. It would be nice if I got me some guidance cause this writing app is so nice.

**Comment by TheJackiMonster** [comment]
You are using Windows 7, right? Because someone else already reported that it doesn't work on Windows 7 properly. I'm not sure if it works on Windows 8/8.1 but Windows 10 should work fine (as well as most Linux distributions). Otherwise if you don't want to change OS which I totally understand, you have following options:
- [Running Manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows)
- Running the previous [version 0.11.0](https://github.com/olivierkes/manuskript/releases/tag/0.11.0)

Maybe the next release will run on Windows 7 again but I can't promise that because I don't have any older Windows version to test compatibility. ^^'

Anyway thanks for sharing the error report. This could actually help with a potential fix.

**Comment by TheJackiMonster** [comment]
Wait, can you try deleting the "ucrtbase.dll" in the directory you extracted Manuskript 0.12.0 to? Maybe this changes the error report.

**Comment by LiegeVon** [comment]
> You are using Windows 7, right? Because someone else already reported that it doesn't work on Windows 7 properly. I'm not sure if it works on Windows 8/8.1 but Windows 10 should work fine (as well as most Linux distributions). Otherwise if you don't want to change OS which I totally understand, you have following options:
> 
> * [Running Manuskript from source](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows)
> * Running the previous [version 0.11.0](https://github.com/olivierkes/manuskript/releases/tag/0.11.0)
> 
> Maybe the next release will run on Windows 7 again but I can't promise that because I don't have any older Windows version to test compatibility. ^^'
> 
> Anyway thanks for sharing the error report. This could actually help with a potential fix.

oh i am on window 8 but hot damn thanks for the suggestion man, ill try

**Comment by LiegeVon** [comment]
> Wait, can you try deleting the "ucrtbase.dll" in the directory you extracted Manuskript 0.12.0 to? Maybe this changes the error report.

holy guacamole, I actually tried this and it works wonder. Thanks man, I appreciate the help.

**Comment by TheJackiMonster** [comment]
> > Wait, can you try deleting the "ucrtbase.dll" in the directory you extracted Manuskript 0.12.0 to? Maybe this changes the error report.
> 
> holy guacamole, I actually tried this and it works wonder. Thanks man, I appreciate the help.

That is good news. Then I will add the step to remove this library in particular to the Windows packaging process and the next release should work out of the box on your system, hopefully. ^^

**Comment by TheJackiMonster** [comment]
I added the fix now for the build script with this commit: 01706dc887931523f49727c59fb2c559d32672d0
