### ISSUE TITLE
Open in new tab doesn't work from tree

### ISSUE THREAD

**Issue by Vidyut** [olivierkes/manuskript#919]
Using 0.12.0 - Ubuntu, everything I can think of is updated.

If the folder is in index cards view and I right click and open the text in a new tab, it works. If I do the same for the same text files from the left side list/tree, it opens as though the text were normally selected and not in a new tab.

Not a major problem, but definitely a bug.

**Comment by akademy** [comment]
Still a bug in 0.14.0

You can avoid the problem by holding down the control key and selecting a textfile - this will open in a new tab.

The problem with the menu item is it selects the textfile you are clicking on before it opens the popup menu. Then, in the open tab code (mainEditor.py:219) it checks to see if that text file is already open, if it is then it selects it rather than opening a new tab - unfortunately it will always be open because it just opened it.

The more I think about this the more difficult it seems to fix... Perhaps the best solution is to remove the code that stops multiple tabs with the same textfile opening (it might even be useful to see two different positions in a long file). Could add numbers to the tab titles instead (e.g. My Text : 1, My Text : 2)
