### ISSUE TITLE
Different writing/planning methods maybe? Or maybe a way to save custom templates?

### ISSUE THREAD

**Issue by Unlucky-the-13th** [olivierkes/manuskript#944]
I'm loving this software so far. I'm still new at it (and GitHub, so I'm sorry for the hundreds of mistakes I've probably made already) so I may be missing something and not even realizing it. 
I was thinking it would be awesome if there could be more templates for writing methods other than the snowflake method. For example, I really like the 3 act - 9 blocks- 27 chapter approach. I guess it's not super necessary, but it would be really cool to have that or a way to set up the way we like the chapters in that way and be able to save that as a template maybe?
My personal recommendation would be to keep the character and world tabs for sure as well as the note card thing. But set up the chapters to reflect the 3 - 9 - 27. 
Keep up the amazing work. I don't think you all realize just how amazing what you're doing here is.

**Comment by TheJackiMonster** [comment]
It's fine. Thanks for the feedback by the way.

Just as explanation why I will close this issue. The feature you are mentioning sounds quite similar to the open issue #421. So to make it easier for contributors to track which features are requested and which problems occur, we will close duplicate issues. That's all.

So I'd recommend you to add the specific writing method as idea to the discussion in #421 if you think that's necessary. It will also be linked automatically from here because I mentioned the older issue by its id. It's best to search for your own issue first and open a new one if you don't find it or if you request a specific detail which makes it different.

I think technically it's also possible to create custom templates if you copy your projects into the samples directory from Manuskript (at least that was an idea in issue #907). However I agree that it could be more intuitive to use.
