### ISSUE TITLE
Software crashes when I try to add a new character detail.

### ISSUE THREAD

**Issue by Unlucky-the-13th** [olivierkes/manuskript#945]
Hey there.
So, I am trying to set up my characters and the software crashes when I try to add more details in the "Detailed Info" section. 

Also, are there any plans to make the software run without having the text window up while it runs? It's not a huge thing, It's just weird having it up in the background. Thanks! 
Edit: Sorry it posted twice, I'm not sure how that happened and I don't know how to add the "bug" label. I just made the account minutes ago and am a total noob...

**Comment by TheJackiMonster** [comment]
Maybe the author of an issue can't tag it as bug and this is an issue with Github. Sorry for the confusion. ^^'

Okay, it could be that your crash is related to other issues in the past. So it's likely that it has been fixed already. You could verify that by trying to [run Manuskript from source code](https://github.com/olivierkes/manuskript/wiki/Run-Manuskript-from-Source-Code-on-Windows). Otherwise I recommend waiting for the next release.

By text window you probably mean the console window in the background. This is already addressed in issue #327 and there has been some discussion how to solve this. In the past it was mostly related to debugging purposes but we got some logging functionality with the latest version. So maybe we can solve this issue in the future.

**Comment by Irvinehimself** [comment]
Here is a *traceback* for the above bug:

```
CRITICAL> An unhandled exception has occurred!
Traceback (most recent call last):
  File "/usr/share/manuskript/manuskript/models/characterPOVModel.py", line 17, in filterAcceptsRow
    return self.sourceModel().pov(sourceRow)
  File "/usr/share/manuskript/manuskript/models/characterModel.py", line 139, in pov
    return self.character(row).pov()
  File "/usr/share/manuskript/manuskript/models/characterModel.py", line 124, in character
    return self.characters[row]
IndexError: list index out of range
```

For reference, I am on Arch Linux with Gnome/Wayland, and the following software versions:

```
    Manuskript  0.12.0
     Python 3.9.7
     PyQt 5.15.6
     Qt 5.15.2
```

Irvine

(Note, I also built the *git* version of Manuskript, and still had the same problem.)

**Comment by TheJackiMonster** [comment]
@Irvinehimself Can you try running it from source and looking for the issue? (Basically cloning the repository and running bin/manuskript with python3) Because the line in characterPOVModel.py was already changed. So either it should be fixed or something else is causing it.

**Comment by TheJackiMonster** [comment]
Ah.. the problem with the AUR package is that it pulls from the master branch which is identical to the latest release binaries. Ok, then the issue seems to be solved actually in the develop branch.

**Comment by Unlucky-the-13th** [comment]
> Ah.. the problem with the AUR package is that it pulls from the master branch which is identical to the latest release binaries. Ok, then the issue seems to be solved actually in the develop branch.

So itll be fixed in the next version?

**Comment by TheJackiMonster** [comment]
Yes
