### ISSUE TITLE
Stripping down the install for low resource machines

### ISSUE THREAD

**Issue by tinkicker** [olivierkes/manuskript#956]
Hi, @olivierkes ,
Since this is my first comment here, I will take a moment to appreciate all of your work! I have been reading a lot of the history of this project through the other issues, and what you are building is wonderful. As an owner of Scrivener on both Windows and iOS, and a user of same on Linux through WINE...I prefer Manuskript. So far the features have been on par with Scrivener where I need them to be while not being bloated. Plus, there is the hope of more great features to come!

Well done.

That said, this issue is in reference to this page in the wiki: [https://github.com/olivierkes/manuskript/wiki/Notes-for-linux-packagers:-removable-files](url). That is quite a list of files! My question and suggestion is could there be a script created that would uninstall all of the unnecessary files with one button?

I don't mind experimenting...God knows I've done tons of it in converting my Acer C710 from Chromebook to Linux laptop. But I've screwed it up so many times...I'm getting tired of redoing things lol.

My little Acer is old and slow like me but it's perfect for writing...it can't play games very well at all so no diversions! It needs all the help it can get. Thank you for reading!

**Comment by TheJackiMonster** [comment]
Thanks for the feedback. ^^

I think the packages on Linux (.deb, .rpm, flatpak and snap) don't use PyInstaller anymore (maybe this was different in version 0.5.0 which is referenced in the wiki article). So using the usual package manager (apt, dnf, flatpak or snap) should remove all installed files properly.

On Windows we still use the PyInstaller because it creates a binary which includes Python for the system of the user. This isn't really necessary on Linux because most distributions already have Python installed and/or it's extremely easy to install it. Also the package manager usually sees it as dependency of Manuskript and takes care of that automatically.

The additional files of PyInstaller were actually a problem with the latest release on Windows but I've mostly taken care of it. I use a script to create the Windows binaries through a generated WINE prefix on Linux and it will remove most additional files automatically before creating the archive.

**Comment by tinkicker** [comment]
So is the idea basically that I just need to check for the presence of
those files, and that most of them shouldn't even have made it in, in the
beginning? That is how I interpret your explanation.

And as a PS, I'll slip in that I'd LOVE a way to scale down the size of the
left-hand row of icons (the General, Summary, etc. ones). The display on my
little writing machine is 1366x768 and they look misproportioned as-is.
I've filed a request for that on GitHub but I'm, well, cheating the system.
Call it a post-Halloween trick.😛

Thank you so much for taking the time to respond here. Have a wonderful day!
K B Tidwell

**Comment by TheJackiMonster** [comment]
> So is the idea basically that I just need to check for the presence of those files, and that most of them shouldn't even have made it in, in the beginning?

So if you have installed Manuskript on Linux via package or store, don't worry about it. Just use the package manager or store to uninstall and they should be gone. On Windows I would recommend removing the extracted folder from the .zip file as a whole. All files should be in there anyway except your own projects. If you have installed it on Linux from the .tar.gz-archive, the solution is similar to Windows but that's more uncommon.

> And as a PS, I'll slip in that I'd LOVE a way to scale down the size of the
left-hand row of icons (the General, Summary, etc. ones). The display on my
little writing machine is 1366x768 and they look misproportioned as-is.

Yes, I agree. I had used a small laptop in the past with a similar screen resolution. So I know this problem. I'm currently working on a refactored version of Manuskript replacing pretty much all of the UI because it will use a different framework instead of Qt (see issue #836). It will most likely use newer responsive components which will make it to even adapt to screen sizes of a phone (because this might also address the request of making a mobile app to some degree).

Anyway this means, there is some effort in the background regarding smaller screen sizes. I just can't promise when it will arrive because of some other projects I'm working on. ^^'

Have a great day!
Jacki
